In [4]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.7.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.47)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.7.0-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 8.6 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.7.0

In [5]:
# Import necessary libraries
import optuna
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source


# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']


# Load the dataset
df = pd.read_csv(url, names=columns)
df.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
331,2,87,58,16,52,32.7,0.166,25,0
646,1,167,74,17,144,23.4,0.447,33,1
61,8,133,72,0,0,32.9,0.270,39,1
317,3,182,74,0,0,30.5,0.345,29,1
670,6,165,68,26,168,33.6,0.631,49,0

In [6]:
# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f"Training set shape: {X_train.shape}")
print(f"Test set shape: {X_test.shape}")

Training set shape: (537, 8)
Test set shape: (231, 8)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
  # Suggest the values for the hyperparameters
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  # Create the RandomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=42
  )

  # Perform 3-fold cross-validation and calculte accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

  return score

In [27]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler()) # We aim at maximizing the accuracy
study.optimize(objective, n_trials=50) # Run 50 trials to find the best hyperparameters

[I 2026-03-01 18:07:14,359] A new study created in memory with name: no-name-7931fb5f-7fad-44ba-9ff2-db18ff317257
[I 2026-03-01 18:07:16,147] Trial 0 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 182, 'max_depth': 9}. Best is trial 0 with value: 0.7616387337057727.
[I 2026-03-01 18:07:17,782] Trial 1 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 133, 'max_depth': 15}. Best is trial 1 with value: 0.7746741154562383.
[I 2026-03-01 18:07:19,182] Trial 2 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 12}. Best is trial 1 with value: 0.7746741154562383.
[I 2026-03-01 18:07:20,284] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 160, 'max_depth': 5}. Best is trial 1 with value: 0.7746741154562383.
[I 2026-03-01 18:07:21,074] Trial 4 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 137, 'max_depth': 6}. Best is trial 1 with value: 0.7746741154562383.
[I 2026-03-01 18:07:22,248] Trial 5 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 195, 'max_depth': 15}. Best is trial 5 with value: 0.7765363128491621.
[I 2026-03-01 18:07:23,342] Trial 6 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 178, 'max_depth': 8}. Best is trial 5 with value: 0.7765363128491621.
[I 2026-03-01 18:07:23,972] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 19}. Best is trial 5 with value: 0.7765363128491621.
[I 2026-03-01 18:07:24,752] Trial 8 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 132, 'max_depth': 7}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:25,546] Trial 9 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 134, 'max_depth': 7}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:25,903] Trial 10 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 65, 'max_depth': 3}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:26,516] Trial 11 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 98, 'max_depth': 10}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:27,139] Trial 12 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 109, 'max_depth': 6}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:27,544] Trial 13 finished with value: 0.756052141527002 and parameters: {'n_estimators': 71, 'max_depth': 3}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:28,315] Trial 14 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 125, 'max_depth': 12}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:29,219] Trial 15 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 159, 'max_depth': 7}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:29,771] Trial 16 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 86, 'max_depth': 10}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:30,899] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 121, 'max_depth': 14}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:31,383] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 53, 'max_depth': 5}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:32,704] Trial 19 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 8}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:33,443] Trial 20 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 19}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:34,237] Trial 21 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 20}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:34,912] Trial 22 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 18}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:35,994] Trial 23 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 17}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:37,137] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 164, 'max_depth': 17}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:38,529] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 135, 'max_depth': 13}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:39,689] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 151, 'max_depth': 10}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:41,211] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 174, 'max_depth': 16}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:42,541] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 129, 'max_depth': 11}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:44,356] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 116, 'max_depth': 8}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:46,450] Trial 30 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 144, 'max_depth': 4}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:47,683] Trial 31 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 125, 'max_depth': 20}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:49,338] Trial 32 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 20}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:51,415] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 17}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:53,066] Trial 34 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 106, 'max_depth': 18}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:54,961] Trial 35 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 153, 'max_depth': 9}. Best is trial 8 with value: 0.7802607076350093.
[I 2026-03-01 18:07:56,405] Trial 36 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 115, 'max_depth': 15}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:07:58,622] Trial 37 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 98, 'max_depth': 15}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:00,999] Trial 38 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 116, 'max_depth': 16}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:02,279] Trial 39 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 126, 'max_depth': 14}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:04,333] Trial 40 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 195, 'max_depth': 19}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:05,871] Trial 41 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 138, 'max_depth': 17}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:07,251] Trial 42 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 131, 'max_depth': 7}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:08,467] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 117, 'max_depth': 14}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:10,013] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 110, 'max_depth': 5}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:12,513] Trial 45 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 140, 'max_depth': 12}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:13,380] Trial 46 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 97, 'max_depth': 18}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:14,560] Trial 47 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 166, 'max_depth': 16}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:15,583] Trial 48 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 129, 'max_depth': 6}. Best is trial 36 with value: 0.7821229050279329.
[I 2026-03-01 18:08:16,115] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 15}. Best is trial 36 with value: 0.7821229050279329.

In [10]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 133, 'max_depth': 18}

In [13]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparamters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f"Test accuracy with best hyperparameters: {test_accuracy:.2f}")

Test accuracy with best hyperparameters: 0.74

## Samplers in Optuna

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
  # Suggest values for the hyperparameters
  n_estimators = trial.suggest_int('n_estimators', 50,200)
  max_depth = trial.suggest_int('max_depth',3,20)

  # Create the RandomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=42
  )

  # Perform 3-fold cross-validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

  return score # Return the accuracy score for Optuna to maximize

In [15]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler()) # We aim to maximize accuracy
study.optimize(objective, n_trials=50) # Run trials to find the best hyperparameters

[I 2026-03-01 17:43:41,613] A new study created in memory with name: no-name-10373ed7-0272-4d7d-81b6-190e1c58c3ed
[I 2026-03-01 17:43:43,570] Trial 0 finished with value: 0.756052141527002 and parameters: {'n_estimators': 183, 'max_depth': 6}. Best is trial 0 with value: 0.756052141527002.
[I 2026-03-01 17:43:45,216] Trial 1 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 18}. Best is trial 1 with value: 0.7690875232774674.
[I 2026-03-01 17:43:46,724] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 18}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:43:48,784] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 190, 'max_depth': 8}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:43:51,748] Trial 4 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 161, 'max_depth': 9}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:43:52,461] Trial 5 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 50, 'max_depth': 9}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:43:53,650] Trial 6 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 118, 'max_depth': 18}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:43:55,245] Trial 7 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 14}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:43:56,492] Trial 8 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 120, 'max_depth': 12}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:43:57,684] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 117, 'max_depth': 10}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:43:58,979] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 131, 'max_depth': 13}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:00,094] Trial 11 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 113, 'max_depth': 8}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:01,329] Trial 12 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 128, 'max_depth': 9}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:03,460] Trial 13 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 175, 'max_depth': 9}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:05,695] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 127, 'max_depth': 14}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:06,418] Trial 15 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 54, 'max_depth': 18}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:07,773] Trial 16 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 20}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:08,355] Trial 17 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 51, 'max_depth': 10}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:09,681] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 139, 'max_depth': 5}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:11,021] Trial 19 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 145, 'max_depth': 3}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:11,879] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 82, 'max_depth': 14}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:12,715] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 17}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:14,543] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 181, 'max_depth': 13}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:15,593] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 104, 'max_depth': 19}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:17,697] Trial 24 finished with value: 0.756052141527002 and parameters: {'n_estimators': 156, 'max_depth': 3}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:18,649] Trial 25 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 50, 'max_depth': 12}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:20,399] Trial 26 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 135, 'max_depth': 15}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:22,119] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 170, 'max_depth': 17}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:23,824] Trial 28 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 172, 'max_depth': 12}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:25,633] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 178, 'max_depth': 18}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:26,226] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 57, 'max_depth': 18}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:27,394] Trial 31 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 124, 'max_depth': 4}. Best is trial 6 with value: 0.7765363128491621.
[I 2026-03-01 17:44:28,842] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 20}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:29,623] Trial 33 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 86, 'max_depth': 3}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:32,247] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 152, 'max_depth': 17}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:33,729] Trial 35 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 91, 'max_depth': 8}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:34,975] Trial 36 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 125, 'max_depth': 7}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:35,612] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 64, 'max_depth': 17}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:37,354] Trial 38 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 182, 'max_depth': 6}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:38,291] Trial 39 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 92, 'max_depth': 18}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:39,162] Trial 40 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 88, 'max_depth': 14}. Best is trial 32 with value: 0.7783985102420856.
[I 2026-03-01 17:44:40,602] Trial 41 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 121, 'max_depth': 18}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:41,243] Trial 42 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 11}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:42,358] Trial 43 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 122, 'max_depth': 4}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:43,233] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 90, 'max_depth': 6}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:44,914] Trial 45 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 100, 'max_depth': 8}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:47,367] Trial 46 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 154, 'max_depth': 20}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:49,296] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 196, 'max_depth': 14}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:50,634] Trial 48 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 154, 'max_depth': 3}. Best is trial 41 with value: 0.7802607076350093.
[I 2026-03-01 17:44:52,236] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 153, 'max_depth': 10}. Best is trial 41 with value: 0.7802607076350093.

In [16]:
# Print the best result
print(f"Best trial accuracy: {study.best_trial.value}")
print(f"Best Hyperparameters: {study.best_trial.params}")

Best trial accuracy: 0.7802607076350093
Best Hyperparameters: {'n_estimators': 121, 'max_depth': 18}

In [18]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f"Test accuracy with best hyperparameters: {test_accuracy:.2f}")

Test accuracy with best hyperparameters: 0.74

In [19]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [20]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-03-01 17:57:18,644] A new study created in memory with name: no-name-b45c0ab9-aed1-41cc-8b35-622af35d2de1
[I 2026-03-01 17:57:19,596] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-01 17:57:21,327] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-03-01 17:57:21,820] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:22,934] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:23,557] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:23,867] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:24,724] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:25,640] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:26,811] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:28,645] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:30,016] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:31,219] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:32,343] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-03-01 17:57:32,634] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-01 17:57:33,252] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-03-01 17:57:33,558] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [21]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [22]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [31]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [32]:
# 1. Optimizing History
plot_optimization_history(study).show()

In [34]:
# 2. Parallel coordinates plot
plot_parallel_coordinate(study).show()

In [35]:
# 3. Slice plot
plot_slice(study).show()

In [36]:
# 4. Contour Plot
plot_contour(study).show()

In [30]:
# 5. Hyperparamter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [37]:
# Importing Multiple ML models
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [62]:
# Define the objective function for Optuna
def objective(trial):
  # Choose the algorithm to tune
  classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

  if classifier_name == 'SVM':
    # SVM Hyperparameters
    c = trial.suggest_float('C', 0.1, 100, log=True)
    kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

    model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

  elif classifier_name == 'RandomForest':
    # Random Forest Hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        bootstrap=bootstrap,
        random_state=42
    )

  elif classifier_name == 'GradientBoosting':
    # Gradient Boosting Hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

    model = GradientBoostingClassifier(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )

  # Perform cross-validation and return the mean accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
  return score

In [63]:
# Create a study and optimize it
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-03-01 19:58:19,936] A new study created in memory with name: no-name-c1dcff19-a8d3-46a6-a649-6913e9d18b90
[I 2026-03-01 19:58:28,015] Trial 0 finished with value: 0.7579143389199254 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 152, 'learning_rate': 0.014378076296455, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.7579143389199254.
[I 2026-03-01 19:58:30,000] Trial 1 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 125, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.7653631284916201.
[I 2026-03-01 19:58:32,604] Trial 2 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 177, 'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 1 with value: 0.7653631284916201.
[I 2026-03-01 19:58:33,682] Trial 3 finished with value: 0.7802607076350093 and parameters: {'classifier': 'RandomForest', 'n_estimators': 99, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:33,792] Trial 4 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 49.28216258988362, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:33,924] Trial 5 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.13944619528309776, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:40,101] Trial 6 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 300, 'learning_rate': 0.01656186933218578, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:40,135] Trial 7 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 1.9543546443008035, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:44,589] Trial 8 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 200, 'learning_rate': 0.017279195237242605, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:44,930] Trial 9 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 54, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:45,176] Trial 10 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 52, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:45,215] Trial 11 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 1.710811607998755, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7802607076350093.
[I 2026-03-01 19:58:45,268] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.6045764913883884, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:45,374] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 20.830355127797482, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:45,506] Trial 14 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 25.64640441275374, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:45,576] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.449625458164993, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:45,634] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.851723328252921, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:45,675] Trial 17 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.49714134497879925, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:45,782] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.031310367635815, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:46,056] Trial 19 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 65.89925756712891, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:49,280] Trial 20 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 253, 'learning_rate': 0.2566554840470426, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:49,477] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 22.343812195350623, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:49,566] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.869137995774767, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:49,769] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 23.62888673067659, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:49,824] Trial 24 finished with value: 0.7318435754189944 and parameters: {'classifier': 'SVM', 'C': 0.8851355840790248, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:49,880] Trial 25 finished with value: 0.6834264432029795 and parameters: {'classifier': 'SVM', 'C': 88.27428813341032, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:50,017] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.46424510367544, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:50,213] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 36.227766167099254, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:53,026] Trial 28 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 235, 'learning_rate': 0.14277422110117086, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:53,074] Trial 29 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.6417153375475797, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:56,557] Trial 30 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 291, 'learning_rate': 0.055744902245367246, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:56,625] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.956866119118088, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:56,697] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 10.10389820801086, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:56,831] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 30.72869298390536, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:57,980] Trial 34 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 215, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:58,074] Trial 35 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 15.533300034487938, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:58,117] Trial 36 finished with value: 0.7206703910614526 and parameters: {'classifier': 'SVM', 'C': 6.188809418720956, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:58,700] Trial 37 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 99, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:58,739] Trial 38 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 2.48390661836182, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:58:58,818] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 11.970840697257426, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:06,202] Trial 40 finished with value: 0.7206703910614526 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 257, 'learning_rate': 0.054739656391903285, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:06,258] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.8069101169484565, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:06,319] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.593760933858769, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:06,373] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.6989614663951946, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:06,537] Trial 44 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 31.851458498226172, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:07,306] Trial 45 finished with value: 0.7765363128491619 and parameters: {'classifier': 'RandomForest', 'n_estimators': 159, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:07,358] Trial 46 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 47.05443406889651, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:07,448] Trial 47 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 16.131461480965594, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:07,484] Trial 48 finished with value: 0.7243947858472999 and parameters: {'classifier': 'SVM', 'C': 1.4121487879507661, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:07,946] Trial 49 finished with value: 0.7839851024208566 and parameters: {'classifier': 'RandomForest', 'n_estimators': 93, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 12 with value: 0.7858472998137801.
[I 2026-03-01 19:59:07,977] Trial 50 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10332130065942711, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 50 with value: 0.7877094972067038.
[I 2026-03-01 19:59:08,010] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15221107973462217, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:08,043] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1345473331668964, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:08,084] Trial 53 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.101550422561354, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:08,117] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23035049125153742, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:08,150] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2475517000750045, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:08,183] Trial 56 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2349211017729608, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:08,223] Trial 57 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.29165361878197227, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,189] Trial 58 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 130, 'learning_rate': 0.04877961132616837, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,222] Trial 59 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21666715536906164, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,266] Trial 60 finished with value: 0.7765363128491619 and parameters: {'classifier': 'SVM', 'C': 0.19065991369710109, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,299] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2384938565571272, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,332] Trial 62 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3720002894998981, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,371] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14925018529937914, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,402] Trial 64 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14503687027089926, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,433] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1332448504662912, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,466] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14286677114022564, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,499] Trial 67 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13240139852309596, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:10,532] Trial 68 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1534496854848906, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:12,130] Trial 69 finished with value: 0.7635009310986964 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 189, 'learning_rate': 0.10844164234136243, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:12,162] Trial 70 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1670179558526199, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:12,195] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14231690348167003, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:12,229] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12968858875423706, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:12,264] Trial 73 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4492017881388253, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:12,298] Trial 74 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 0.15703503063057253, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:12,330] Trial 75 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12572744835821892, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:14,493] Trial 76 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 272, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:14,544] Trial 77 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.32378223023416114, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:14,600] Trial 78 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7675652149729739, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:14,664] Trial 79 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.17649329613924972, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:14,712] Trial 80 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13063595094887812, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.
[I 2026-03-01 19:59:14,762] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14443700592104672, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 51 with value: 0.7895716945996275.

In [64]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters: ", best_trial.params)
print("Best trial accuracy: ", best_trial.value)

Best trial parameters:  {'classifier': 'SVM', 'C': 0.15221107973462217, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy:  0.7895716945996275

In [65]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.757914,2026-03-01 19:58:19.942848,2026-03-01 19:58:28.015251,0 days 00:00:08.072403,NaN,NaN,GradientBoosting,NaN,NaN,0.014378,18.0,4.0,3.0,152.0,COMPLETE
1,1,0.765363,2026-03-01 19:58:28.018062,2026-03-01 19:58:30.000548,0 days 00:00:01.982486,NaN,False,RandomForest,NaN,NaN,NaN,20.0,3.0,9.0,125.0,COMPLETE
2,2,0.759777,2026-03-01 19:58:30.010740,2026-03-01 19:58:32.604498,0 days 00:00:02.593758,NaN,True,RandomForest,NaN,NaN,NaN,18.0,10.0,10.0,177.0,COMPLETE
3,3,0.780261,2026-03-01 19:58:32.607407,2026-03-01 19:58:33.682475,0 days 00:00:01.075068,NaN,False,RandomForest,NaN,NaN,NaN,6.0,2.0,2.0,99.0,COMPLETE
4,4,0.715084,2026-03-01 19:58:33.683888,2026-03-01 19:58:33.792574,0 days 00:00:00.108686,49.282163,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.711359,2026-03-01 19:59:18.118064,2026-03-01 19:59:18.150736,0 days 00:00:00.032672,0.131115,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.785847,2026-03-01 19:59:18.151898,2026-03-01 19:59:18.183841,0 days 00:00:00.031943,0.272796,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.785847,2026-03-01 19:59:18.185267,2026-03-01 19:59:18.218640,0 days 00:00:00.033373,0.201624,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.789572,2026-03-01 19:59:18.219830,2026-03-01 19:59:18.259045,0 days 00:00:00.039215,0.152457,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.789572,2026-03-01 19:59:18.260911,2026-03-01 19:59:18.291315,0 days 00:00:00.030404,0.120231,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [66]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
RandomForest        11
GradientBoosting    10
Name: count, dtype: int64

In [67]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.745438
RandomForest        0.766040
SVM                 0.775216
Name: value, dtype: float64

In [68]:
# 1. Optimization History
plot_optimization_history(study).show()

In [69]:
# 2. Slice plot
plot_slice(study).show()

In [70]:
# Hyperparameter Impotance
plot_param_importances(study).show()

In [11]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function
def objective(trial):
  # Hyperparameter search space
  param = {
    'verbosity': 0,
    'objective': 'multi:softprob',
    'num_class': 3,
    'eval_metric': 'mlogloss', # Ensure that the eval_metric is specified here
    'booster': 'gbtree',
    'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
    'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
    'eta': trial.suggest_float('eta', .01, 0.3),
    'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
    'max_depth': trial.suggest_int('max_depth', 3, 9),
    'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
    'subsample': trial.suggest_float('subsample', 0.4, 1.0),
    'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
    'n_estimators': 300
  }

  # Create DMatrix for XGBoost
  dtrain = xgb.DMatrix(X_train, label=y_train)
  dtest = xgb.DMatrix(X_test, label=y_test)

  # Define a pruning callback based on evaluation metrics
  pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss") # Match the metric name in the evals list

  # Train the model
  bst = xgb.train(
      param,
      dtrain,
      num_boost_round=300,
      evals=[(dtrain, "train"), (dtest, "eval")], # Ensure the eval datasets and names are specified
      early_stopping_rounds=30,
      callbacks=[pruning_callback]
  )

  # Predict on the test set
  preds = bst.predict(dtest)
  best_preds = [int(np.argmax(line)) for line in preds]

  # Return accuracy as the objective value
  accuracy =  accuracy_score(y_test, best_preds)
  return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

[I 2026-03-02 05:11:12,208] A new study created in memory with name: no-name-b37561ea-4aa5-46b5-a13c-04cfd1c8441e

[0]	train-mlogloss:0.84112	eval-mlogloss:0.82496
[1]	train-mlogloss:0.66459	eval-mlogloss:0.63273
[2]	train-mlogloss:0.53586	eval-mlogloss:0.49834
[3]	train-mlogloss:0.43663	eval-mlogloss:0.39317
[4]	train-mlogloss:0.36935	eval-mlogloss:0.32289
[5]	train-mlogloss:0.31746	eval-mlogloss:0.26476
[6]	train-mlogloss:0.28379	eval-mlogloss:0.22807
[7]	train-mlogloss:0.27306	eval-mlogloss:0.21790
[8]	train-mlogloss:0.24724	eval-mlogloss:0.18864
[9]	train-mlogloss:0.23886	eval-mlogloss:0.17538
[10]	train-mlogloss:0.23139	eval-mlogloss:0.16667
[11]	train-mlogloss:0.23124	eval-mlogloss:0.16762
[12]	train-mlogloss:0.23007	eval-mlogloss:0.16660
[13]	train-mlogloss:0.22943	eval-mlogloss:0.16590
[14]	train-mlogloss:0.22921	eval-mlogloss:0.16659
[15]	train-mlogloss:0.22800	eval-mlogloss:0.16537
[16]	train-mlogloss:0.22732	eval-mlogloss:0.16285
[17]	train-mlogloss:0.22703	eval-mlogloss:0.16360
[18]	train-mlogloss:0.22725	eval-mlogloss:0.16368
[19]	train-mlogloss:0.22641	eval-mlogloss:0.16318
[20]	train-mlogloss:0.22644	eval-mlogloss:0.16321
[21]	train-mlogloss:0.22627	eval-mlogloss:0.16257
[22]	train-mlogloss:0.22078	eval-mlogloss:0.15554
[23]	train-mlogloss:0.21951	eval-mlogloss:0.15420
[24]	train-mlogloss:0.21870	eval-mlogloss:0.15294
[25]	train-mlogloss:0.21797	eval-mlogloss:0.15259
[26]	train-mlogloss:0.21806	eval-mlogloss:0.15270
[27]	train-mlogloss:0.21771	eval-mlogloss:0.15222
[28]	train-mlogloss:0.21744	eval-mlogloss:0.15214
[29]	train-mlogloss:0.21722	eval-mlogloss:0.15144
[30]	train-mlogloss:0.21716	eval-mlogloss:0.15159
[31]	train-mlogloss:0.21700	eval-mlogloss:0.15142
[32]	train-mlogloss:0.21695	eval-mlogloss:0.15164
[33]	train-mlogloss:0.21682	eval-mlogloss:0.15139
[34]	train-mlogloss:0.21635	eval-mlogloss:0.14946
[35]	train-mlogloss:0.21628	eval-mlogloss:0.14959
[36]	train-mlogloss:0.21637	eval-mlogloss:0.14976
[37]	train-mlogloss:0.21554	eval-mlogloss:0.15005
[38]	train-mlogloss:0.21555	eval-mlogloss:0.15009
[39]	train-mlogloss:0.21518	eval-mlogloss:0.14975
[40]	train-mlogloss:0.21480	eval-mlogloss:0.14925
[41]	train-mlogloss:0.21471	eval-mlogloss:0.14922
[42]	train-mlogloss:0.21450	eval-mlogloss:0.14803
[43]	train-mlogloss:0.21468	eval-mlogloss:0.14824
[44]	train-mlogloss:0.21438	eval-mlogloss:0.14813
[45]	train-mlogloss:0.21411	eval-mlogloss:0.14789
[46]	train-mlogloss:0.21355	eval-mlogloss:0.14713
[47]	train-mlogloss:0.21294	eval-mlogloss:0.14691
[48]	train-mlogloss:0.21300	eval-mlogloss:0.14696
[49]	train-mlogloss:0.21277	eval-mlogloss:0.14534
[50]	train-mlogloss:0.21039	eval-mlogloss:0.14195
[51]	train-mlogloss:0.21031	eval-mlogloss:0.14133
[52]	train-mlogloss:0.21011	eval-mlogloss:0.14125
[53]	train-mlogloss:0.21013	eval-mlogloss:0.14135
[54]	train-mlogloss:0.20995	eval-mlogloss:0.14108
[55]	train-mlogloss:0.20971	eval-mlogloss:0.14086
[56]	train-mlogloss:0.20958	eval-mlogloss:0.14067
[57]	train-mlogloss:0.20964	eval-mlogloss:0.14067
[58]	train-mlogloss:0.20966	eval-mlogloss:0.14071
[59]	train-mlogloss:0.20935	eval-mlogloss:0.14040
[60]	train-mlogloss:0.20920	eval-mlogloss:0.14037
[61]	train-mlogloss:0.20904	eval-mlogloss:0.14045
[62]	train-mlogloss:0.20905	eval-mlogloss:0.14049
[63]	train-mlogloss:0.20902	eval-mlogloss:0.14028
[64]	train-mlogloss:0.20902	eval-mlogloss:0.14018
[65]	train-mlogloss:0.20933	eval-mlogloss:0.14025
[66]	train-mlogloss:0.20906	eval-mlogloss:0.14022
[67]	train-mlogloss:0.20902	eval-mlogloss:0.14029
[68]	train-mlogloss:0.20898	eval-mlogloss:0.14020
[69]	train-mlogloss:0.20881	eval-mlogloss:0.14000
[70]	train-mlogloss:0.20886	eval-mlogloss:0.14002
[71]	train-mlogloss:0.20888	eval-mlogloss:0.14008
[72]	train-mlogloss:0.20890	eval-mlogloss:0.13999
[73]	train-mlogloss:0.20896	eval-mlogloss:0.13974
[74]	train-mlogloss:0.20884	eval-mlogloss:0.14032
[75]	train-mlogloss:0.20883	eval-mlogloss:0.14041
[76]	train-mlogloss:0.20890	eval-mlogloss:0.14067
[77]	train-mlogloss:0.20885	eval-mlogloss:0.14073
[78]	train-mlogloss:0.20907	eval-mlogloss:0.14106
[79]	train-mlogloss:0.20901	eval-mlogloss:0.14105
[80]	train-mlogloss:0.20883	eval-mlogloss:0.14091
[81]	train-mlogloss:0.20888	eval-mlogloss:0.14105
[82]	train-mlogloss:0.20892	eval-mlogloss:0.14112
[83]	train-mlogloss:0.20893	eval-mlogloss:0.14108
[84]	train-mlogloss:0.20864	eval-mlogloss:0.14090
[85]	train-mlogloss:0.20847	eval-mlogloss:0.14067
[86]	train-mlogloss:0.20842	eval-mlogloss:0.14062
[87]	train-mlogloss:0.20811	eval-mlogloss:0.14045
[88]	train-mlogloss:0.20782	eval-mlogloss:0.14020
[89]	train-mlogloss:0.20773	eval-mlogloss:0.14003
[90]	train-mlogloss:0.20784	eval-mlogloss:0.14016
[91]	train-mlogloss:0.20784	eval-mlogloss:0.14018
[92]	train-mlogloss:0.20771	eval-mlogloss:0.14001
[93]	train-mlogloss:0.20770	eval-mlogloss:0.13981
[94]	train-mlogloss:0.20774	eval-mlogloss:0.13996
[95]	train-mlogloss:0.20790	eval-mlogloss:0.14016
[96]	train-mlogloss:0.20774	eval-mlogloss:0.14002
[97]	train-mlogloss:0.20762	eval-mlogloss:0.13991
[98]	train-mlogloss:0.20814	eval-mlogloss:0.14115
[99]	train-mlogloss:0.20790	eval-mlogloss:0.14074
[100]	train-mlogloss:0.20786	eval-mlogloss:0.14052
[101]	train-mlogloss:0.20761	eval-mlogloss:0.14025
[102]	train-mlogloss:0.20759	eval-mlogloss:0.14021
[103]	train-mlogloss:0.20751	eval-mlogloss:0.14024

[I 2026-03-02 05:11:14,097] Trial 0 finished with value: 1.0 and parameters: {'lambda': 4.960338084001493e-07, 'alpha': 5.486571438628039e-05, 'eta': 0.2197450675095145, 'gamma': 6.85429596893445e-08, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6070679131016201, 'colsample_bytree': 0.9126435074335836}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04651	eval-mlogloss:1.04747
[1]	train-mlogloss:0.97438	eval-mlogloss:0.97144
[2]	train-mlogloss:0.90844	eval-mlogloss:0.90118
[3]	train-mlogloss:0.84731	eval-mlogloss:0.83701
[4]	train-mlogloss:0.79341	eval-mlogloss:0.78143
[5]	train-mlogloss:0.74263	eval-mlogloss:0.72762
[6]	train-mlogloss:0.69720	eval-mlogloss:0.68150
[7]	train-mlogloss:0.65728	eval-mlogloss:0.63892
[8]	train-mlogloss:0.61978	eval-mlogloss:0.59856
[9]	train-mlogloss:0.58407	eval-mlogloss:0.56078
[10]	train-mlogloss:0.55211	eval-mlogloss:0.52641
[11]	train-mlogloss:0.52289	eval-mlogloss:0.49447
[12]	train-mlogloss:0.50597	eval-mlogloss:0.47790
[13]	train-mlogloss:0.47920	eval-mlogloss:0.44860
[14]	train-mlogloss:0.46456	eval-mlogloss:0.43472
[15]	train-mlogloss:0.44263	eval-mlogloss:0.41138
[16]	train-mlogloss:0.42273	eval-mlogloss:0.38945
[17]	train-mlogloss:0.40688	eval-mlogloss:0.37257
[18]	train-mlogloss:0.38730	eval-mlogloss:0.35198
[19]	train-mlogloss:0.37223	eval-mlogloss:0.33649
[20]	train-mlogloss:0.35545	eval-mlogloss:0.31836
[21]	train-mlogloss:0.33858	eval-mlogloss:0.29911
[22]	train-mlogloss:0.32728	eval-mlogloss:0.28635
[23]	train-mlogloss:0.31289	eval-mlogloss:0.27055
[24]	train-mlogloss:0.29939	eval-mlogloss:0.25555
[25]	train-mlogloss:0.28867	eval-mlogloss:0.24315
[26]	train-mlogloss:0.28062	eval-mlogloss:0.23413
[27]	train-mlogloss:0.27079	eval-mlogloss:0.22315
[28]	train-mlogloss:0.26349	eval-mlogloss:0.21472
[29]	train-mlogloss:0.25396	eval-mlogloss:0.20371
[30]	train-mlogloss:0.24602	eval-mlogloss:0.19435
[31]	train-mlogloss:0.23854	eval-mlogloss:0.18708
[32]	train-mlogloss:0.23112	eval-mlogloss:0.17852
[33]	train-mlogloss:0.22743	eval-mlogloss:0.17393
[34]	train-mlogloss:0.21965	eval-mlogloss:0.16553
[35]	train-mlogloss:0.21463	eval-mlogloss:0.15990
[36]	train-mlogloss:0.20901	eval-mlogloss:0.15415
[37]	train-mlogloss:0.20325	eval-mlogloss:0.14809
[38]	train-mlogloss:0.20010	eval-mlogloss:0.14469
[39]	train-mlogloss:0.19583	eval-mlogloss:0.13936
[40]	train-mlogloss:0.19241	eval-mlogloss:0.13571
[41]	train-mlogloss:0.19106	eval-mlogloss:0.13376
[42]	train-mlogloss:0.18968	eval-mlogloss:0.13136
[43]	train-mlogloss:0.18659	eval-mlogloss:0.12774
[44]	train-mlogloss:0.18337	eval-mlogloss:0.12323
[45]	train-mlogloss:0.18306	eval-mlogloss:0.12278
[46]	train-mlogloss:0.18183	eval-mlogloss:0.12095
[47]	train-mlogloss:0.18092	eval-mlogloss:0.11959
[48]	train-mlogloss:0.17957	eval-mlogloss:0.11794
[49]	train-mlogloss:0.17794	eval-mlogloss:0.11604
[50]	train-mlogloss:0.17654	eval-mlogloss:0.11402
[51]	train-mlogloss:0.17489	eval-mlogloss:0.11196
[52]	train-mlogloss:0.17387	eval-mlogloss:0.11033
[53]	train-mlogloss:0.17339	eval-mlogloss:0.10949
[54]	train-mlogloss:0.17284	eval-mlogloss:0.10948
[55]	train-mlogloss:0.17154	eval-mlogloss:0.10802
[56]	train-mlogloss:0.17137	eval-mlogloss:0.10776
[57]	train-mlogloss:0.17066	eval-mlogloss:0.10669
[58]	train-mlogloss:0.16990	eval-mlogloss:0.10543
[59]	train-mlogloss:0.16960	eval-mlogloss:0.10528
[60]	train-mlogloss:0.16889	eval-mlogloss:0.10445
[61]	train-mlogloss:0.16866	eval-mlogloss:0.10423
[62]	train-mlogloss:0.16765	eval-mlogloss:0.10327
[63]	train-mlogloss:0.16763	eval-mlogloss:0.10288
[64]	train-mlogloss:0.16759	eval-mlogloss:0.10247
[65]	train-mlogloss:0.16616	eval-mlogloss:0.10073
[66]	train-mlogloss:0.16595	eval-mlogloss:0.10042
[67]	train-mlogloss:0.16596	eval-mlogloss:0.10048
[68]	train-mlogloss:0.16515	eval-mlogloss:0.10051
[69]	train-mlogloss:0.16433	eval-mlogloss:0.09915
[70]	train-mlogloss:0.16430	eval-mlogloss:0.09921
[71]	train-mlogloss:0.16420	eval-mlogloss:0.09918
[72]	train-mlogloss:0.16418	eval-mlogloss:0.09906
[73]	train-mlogloss:0.16357	eval-mlogloss:0.09797
[74]	train-mlogloss:0.16337	eval-mlogloss:0.09783
[75]	train-mlogloss:0.16338	eval-mlogloss:0.09792
[76]	train-mlogloss:0.16277	eval-mlogloss:0.09705
[77]	train-mlogloss:0.16258	eval-mlogloss:0.09692
[78]	train-mlogloss:0.16232	eval-mlogloss:0.09684
[79]	train-mlogloss:0.16190	eval-mlogloss:0.09613
[80]	train-mlogloss:0.16191	eval-mlogloss:0.09618
[81]	train-mlogloss:0.16192	eval-mlogloss:0.09614
[82]	train-mlogloss:0.16191	eval-mlogloss:0.09618
[83]	train-mlogloss:0.16169	eval-mlogloss:0.09652
[84]	train-mlogloss:0.16099	eval-mlogloss:0.09568
[85]	train-mlogloss:0.16072	eval-mlogloss:0.09553
[86]	train-mlogloss:0.16078	eval-mlogloss:0.09564
[87]	train-mlogloss:0.16064	eval-mlogloss:0.09555
[88]	train-mlogloss:0.16046	eval-mlogloss:0.09546
[89]	train-mlogloss:0.15997	eval-mlogloss:0.09476
[90]	train-mlogloss:0.15987	eval-mlogloss:0.09471
[91]	train-mlogloss:0.15992	eval-mlogloss:0.09478
[92]	train-mlogloss:0.15960	eval-mlogloss:0.09458
[93]	train-mlogloss:0.15954	eval-mlogloss:0.09434
[94]	train-mlogloss:0.15957	eval-mlogloss:0.09427
[95]	train-mlogloss:0.15941	eval-mlogloss:0.09421
[96]	train-mlogloss:0.15934	eval-mlogloss:0.09416
[97]	train-mlogloss:0.15933	eval-mlogloss:0.09426
[98]	train-mlogloss:0.15916	eval-mlogloss:0.09419
[99]	train-mlogloss:0.15840	eval-mlogloss:0.09350
[100]	train-mlogloss:0.15823	eval-mlogloss:0.09323
[101]	train-mlogloss:0.15741	eval-mlogloss:0.09241
[102]	train-mlogloss:0.15733	eval-mlogloss:0.09231
[103]	train-mlogloss:0.15731	eval-mlogloss:0.09226
[104]	train-mlogloss:0.15726	eval-mlogloss:0.09224
[105]	train-mlogloss:0.15713	eval-mlogloss:0.09199
[106]	train-mlogloss:0.15640	eval-mlogloss:0.09087
[107]	train-mlogloss:0.15646	eval-mlogloss:0.09106
[108]	train-mlogloss:0.15632	eval-mlogloss:0.09094
[109]	train-mlogloss:0.15628	eval-mlogloss:0.09082
[110]	train-mlogloss:0.15620	eval-mlogloss:0.09084
[111]	train-mlogloss:0.15615	eval-mlogloss:0.09086
[112]	train-mlogloss:0.15611	eval-mlogloss:0.09080
[113]	train-mlogloss:0.15587	eval-mlogloss:0.08972
[114]	train-mlogloss:0.15587	eval-mlogloss:0.08933
[115]	train-mlogloss:0.15588	eval-mlogloss:0.08961
[116]	train-mlogloss:0.15591	eval-mlogloss:0.08968
[117]	train-mlogloss:0.15574	eval-mlogloss:0.08937
[118]	train-mlogloss:0.15543	eval-mlogloss:0.08902
[119]	train-mlogloss:0.15534	eval-mlogloss:0.08890
[120]	train-mlogloss:0.15522	eval-mlogloss:0.08868
[121]	train-mlogloss:0.15520	eval-mlogloss:0.08864
[122]	train-mlogloss:0.15506	eval-mlogloss:0.08853
[123]	train-mlogloss:0.15469	eval-mlogloss:0.08792
[124]	train-mlogloss:0.15425	eval-mlogloss:0.08791
[125]	train-mlogloss:0.15414	eval-mlogloss:0.08786
[126]	train-mlogloss:0.15375	eval-mlogloss:0.08811
[127]	train-mlogloss:0.15370	eval-mlogloss:0.08801
[128]	train-mlogloss:0.15374	eval-mlogloss:0.08810
[129]	train-mlogloss:0.15360	eval-mlogloss:0.08806
[130]	train-mlogloss:0.15367	eval-mlogloss:0.08813
[131]	train-mlogloss:0.15366	eval-mlogloss:0.08813
[132]	train-mlogloss:0.15282	eval-mlogloss:0.08704
[133]	train-mlogloss:0.15280	eval-mlogloss:0.08702
[134]	train-mlogloss:0.15280	eval-mlogloss:0.08706
[135]	train-mlogloss:0.15281	eval-mlogloss:0.08692
[136]	train-mlogloss:0.15283	eval-mlogloss:0.08696
[137]	train-mlogloss:0.15271	eval-mlogloss:0.08669
[138]	train-mlogloss:0.15261	eval-mlogloss:0.08655
[139]	train-mlogloss:0.15247	eval-mlogloss:0.08640
[140]	train-mlogloss:0.15248	eval-mlogloss:0.08674
[141]	train-mlogloss:0.15246	eval-mlogloss:0.08634
[142]	train-mlogloss:0.15251	eval-mlogloss:0.08635
[143]	train-mlogloss:0.15239	eval-mlogloss:0.08632
[144]	train-mlogloss:0.15225	eval-mlogloss:0.08629
[145]	train-mlogloss:0.15228	eval-mlogloss:0.08607
[146]	train-mlogloss:0.15227	eval-mlogloss:0.08602
[147]	train-mlogloss:0.15186	eval-mlogloss:0.08525
[148]	train-mlogloss:0.15183	eval-mlogloss:0.08526
[149]	train-mlogloss:0.15172	eval-mlogloss:0.08515
[150]	train-mlogloss:0.15165	eval-mlogloss:0.08517
[151]	train-mlogloss:0.15164	eval-mlogloss:0.08510
[152]	train-mlogloss:0.15151	eval-mlogloss:0.08508
[153]	train-mlogloss:0.15145	eval-mlogloss:0.08499
[154]	train-mlogloss:0.15136	eval-mlogloss:0.08474
[155]	train-mlogloss:0.15126	eval-mlogloss:0.08463
[156]	train-mlogloss:0.15120	eval-mlogloss:0.08451
[157]	train-mlogloss:0.15118	eval-mlogloss:0.08451
[158]	train-mlogloss:0.15108	eval-mlogloss:0.08445
[159]	train-mlogloss:0.15092	eval-mlogloss:0.08444
[160]	train-mlogloss:0.15092	eval-mlogloss:0.08441
[161]	train-mlogloss:0.15080	eval-mlogloss:0.08410
[162]	train-mlogloss:0.15071	eval-mlogloss:0.08408
[163]	train-mlogloss:0.15072	eval-mlogloss:0.08424
[164]	train-mlogloss:0.15074	eval-mlogloss:0.08401
[165]	train-mlogloss:0.15071	eval-mlogloss:0.08403
[166]	train-mlogloss:0.15000	eval-mlogloss:0.08302
[167]	train-mlogloss:0.15001	eval-mlogloss:0.08307
[168]	train-mlogloss:0.15000	eval-mlogloss:0.08305
[169]	train-mlogloss:0.14987	eval-mlogloss:0.08293
[170]	train-mlogloss:0.14984	eval-mlogloss:0.08279
[171]	train-mlogloss:0.14981	eval-mlogloss:0.08277
[172]	train-mlogloss:0.14981	eval-mlogloss:0.08274
[173]	train-mlogloss:0.14970	eval-mlogloss:0.08274
[174]	train-mlogloss:0.14973	eval-mlogloss:0.08288
[175]	train-mlogloss:0.14970	eval-mlogloss:0.08282
[176]	train-mlogloss:0.14953	eval-mlogloss:0.08244
[177]	train-mlogloss:0.14949	eval-mlogloss:0.08237
[178]	train-mlogloss:0.14948	eval-mlogloss:0.08244
[179]	train-mlogloss:0.14948	eval-mlogloss:0.08241
[180]	train-mlogloss:0.14948	eval-mlogloss:0.08180
[181]	train-mlogloss:0.14944	eval-mlogloss:0.08184
[182]	train-mlogloss:0.14945	eval-mlogloss:0.08178
[183]	train-mlogloss:0.14945	eval-mlogloss:0.08186
[184]	train-mlogloss:0.14935	eval-mlogloss:0.08171
[185]	train-mlogloss:0.14936	eval-mlogloss:0.08175
[186]	train-mlogloss:0.14929	eval-mlogloss:0.08163
[187]	train-mlogloss:0.14929	eval-mlogloss:0.08161
[188]	train-mlogloss:0.14931	eval-mlogloss:0.08169
[189]	train-mlogloss:0.14929	eval-mlogloss:0.08191
[190]	train-mlogloss:0.14921	eval-mlogloss:0.08196
[191]	train-mlogloss:0.14918	eval-mlogloss:0.08199
[192]	train-mlogloss:0.14917	eval-mlogloss:0.08201
[193]	train-mlogloss:0.14909	eval-mlogloss:0.08189
[194]	train-mlogloss:0.14898	eval-mlogloss:0.08182
[195]	train-mlogloss:0.14898	eval-mlogloss:0.08177
[196]	train-mlogloss:0.14892	eval-mlogloss:0.08174
[197]	train-mlogloss:0.14891	eval-mlogloss:0.08172
[198]	train-mlogloss:0.14890	eval-mlogloss:0.08150
[199]	train-mlogloss:0.14890	eval-mlogloss:0.08142
[200]	train-mlogloss:0.14886	eval-mlogloss:0.08134
[201]	train-mlogloss:0.14888	eval-mlogloss:0.08129
[202]	train-mlogloss:0.14890	eval-mlogloss:0.08134
[203]	train-mlogloss:0.14888	eval-mlogloss:0.08117
[204]	train-mlogloss:0.14879	eval-mlogloss:0.08114
[205]	train-mlogloss:0.14869	eval-mlogloss:0.08098
[206]	train-mlogloss:0.14860	eval-mlogloss:0.08088
[207]	train-mlogloss:0.14853	eval-mlogloss:0.08077
[208]	train-mlogloss:0.14854	eval-mlogloss:0.08081
[209]	train-mlogloss:0.14847	eval-mlogloss:0.08064
[210]	train-mlogloss:0.14846	eval-mlogloss:0.08026
[211]	train-mlogloss:0.14843	eval-mlogloss:0.08023
[212]	train-mlogloss:0.14831	eval-mlogloss:0.08016
[213]	train-mlogloss:0.14830	eval-mlogloss:0.08020
[214]	train-mlogloss:0.14830	eval-mlogloss:0.08042
[215]	train-mlogloss:0.14832	eval-mlogloss:0.08050
[216]	train-mlogloss:0.14782	eval-mlogloss:0.08076
[217]	train-mlogloss:0.14782	eval-mlogloss:0.08086
[218]	train-mlogloss:0.14742	eval-mlogloss:0.08116
[219]	train-mlogloss:0.14743	eval-mlogloss:0.08113
[220]	train-mlogloss:0.14733	eval-mlogloss:0.08114
[221]	train-mlogloss:0.14721	eval-mlogloss:0.08117
[222]	train-mlogloss:0.14717	eval-mlogloss:0.08120
[223]	train-mlogloss:0.14718	eval-mlogloss:0.08124
[224]	train-mlogloss:0.14716	eval-mlogloss:0.08101
[225]	train-mlogloss:0.14716	eval-mlogloss:0.08105
[226]	train-mlogloss:0.14713	eval-mlogloss:0.08105
[227]	train-mlogloss:0.14713	eval-mlogloss:0.08108
[228]	train-mlogloss:0.14712	eval-mlogloss:0.08102
[229]	train-mlogloss:0.14717	eval-mlogloss:0.08108
[230]	train-mlogloss:0.14714	eval-mlogloss:0.08108
[231]	train-mlogloss:0.14712	eval-mlogloss:0.08106
[232]	train-mlogloss:0.14711	eval-mlogloss:0.08107
[233]	train-mlogloss:0.14704	eval-mlogloss:0.08102
[234]	train-mlogloss:0.14709	eval-mlogloss:0.08122
[235]	train-mlogloss:0.14704	eval-mlogloss:0.08105
[236]	train-mlogloss:0.14707	eval-mlogloss:0.08118
[237]	train-mlogloss:0.14705	eval-mlogloss:0.08123
[238]	train-mlogloss:0.14695	eval-mlogloss:0.08127
[239]	train-mlogloss:0.14693	eval-mlogloss:0.08125
[240]	train-mlogloss:0.14692	eval-mlogloss:0.08093
[241]	train-mlogloss:0.14693	eval-mlogloss:0.08119
[242]	train-mlogloss:0.14690	eval-mlogloss:0.08117

[I 2026-03-02 05:11:15,826] Trial 1 finished with value: 1.0 and parameters: {'lambda': 1.8433525831783102e-05, 'alpha': 7.810803851440684e-06, 'eta': 0.06065607654289753, 'gamma': 0.00717493689129004, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.6625120936048907, 'colsample_bytree': 0.7382742343903381}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.95161	eval-mlogloss:0.94400

[I 2026-03-02 05:11:15,873] Trial 2 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92826	eval-mlogloss:0.94250

[I 2026-03-02 05:11:15,909] Trial 3 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02900	eval-mlogloss:1.03100

[I 2026-03-02 05:11:15,926] Trial 4 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96313	eval-mlogloss:0.98676

[I 2026-03-02 05:11:15,941] Trial 5 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.86816	eval-mlogloss:0.85354

[I 2026-03-02 05:11:15,973] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02362	eval-mlogloss:1.03252

[I 2026-03-02 05:11:16,000] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.93595	eval-mlogloss:0.95173

[I 2026-03-02 05:11:16,012] Trial 8 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.84281	eval-mlogloss:0.84251

[I 2026-03-02 05:11:16,027] Trial 9 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85947	eval-mlogloss:0.84583

[I 2026-03-02 05:11:16,100] Trial 10 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05830	eval-mlogloss:1.05690
[1]	train-mlogloss:1.02086	eval-mlogloss:1.01736
[2]	train-mlogloss:0.98472	eval-mlogloss:0.97967
[3]	train-mlogloss:0.94920	eval-mlogloss:0.94301
[4]	train-mlogloss:0.91646	eval-mlogloss:0.90869
[5]	train-mlogloss:0.88442	eval-mlogloss:0.87426
[6]	train-mlogloss:0.85500	eval-mlogloss:0.84311
[7]	train-mlogloss:0.82760	eval-mlogloss:0.81404
[8]	train-mlogloss:0.80123	eval-mlogloss:0.78573
[9]	train-mlogloss:0.77532	eval-mlogloss:0.75798
[10]	train-mlogloss:0.75068	eval-mlogloss:0.73262
[11]	train-mlogloss:0.72706	eval-mlogloss:0.70799
[12]	train-mlogloss:0.70521	eval-mlogloss:0.68551
[13]	train-mlogloss:0.68362	eval-mlogloss:0.66260
[14]	train-mlogloss:0.66288	eval-mlogloss:0.64099
[15]	train-mlogloss:0.64263	eval-mlogloss:0.61941
[16]	train-mlogloss:0.62363	eval-mlogloss:0.59908
[17]	train-mlogloss:0.60547	eval-mlogloss:0.57958
[18]	train-mlogloss:0.58960	eval-mlogloss:0.56409
[19]	train-mlogloss:0.57288	eval-mlogloss:0.54686
[20]	train-mlogloss:0.55632	eval-mlogloss:0.52887
[21]	train-mlogloss:0.54040	eval-mlogloss:0.51108
[22]	train-mlogloss:0.52520	eval-mlogloss:0.49519
[23]	train-mlogloss:0.51073	eval-mlogloss:0.47969
[24]	train-mlogloss:0.49890	eval-mlogloss:0.46684
[25]	train-mlogloss:0.48607	eval-mlogloss:0.45214
[26]	train-mlogloss:0.47329	eval-mlogloss:0.43826
[27]	train-mlogloss:0.46131	eval-mlogloss:0.42588
[28]	train-mlogloss:0.44935	eval-mlogloss:0.41311
[29]	train-mlogloss:0.43782	eval-mlogloss:0.40030
[30]	train-mlogloss:0.42697	eval-mlogloss:0.38874
[31]	train-mlogloss:0.41620	eval-mlogloss:0.37674
[32]	train-mlogloss:0.40621	eval-mlogloss:0.36537
[33]	train-mlogloss:0.39641	eval-mlogloss:0.35435
[34]	train-mlogloss:0.38648	eval-mlogloss:0.34397
[35]	train-mlogloss:0.37854	eval-mlogloss:0.33503
[36]	train-mlogloss:0.37044	eval-mlogloss:0.32620
[37]	train-mlogloss:0.36216	eval-mlogloss:0.31734
[38]	train-mlogloss:0.35622	eval-mlogloss:0.31089
[39]	train-mlogloss:0.34846	eval-mlogloss:0.30241
[40]	train-mlogloss:0.34081	eval-mlogloss:0.29396
[41]	train-mlogloss:0.33397	eval-mlogloss:0.28602
[42]	train-mlogloss:0.32795	eval-mlogloss:0.28001
[43]	train-mlogloss:0.32121	eval-mlogloss:0.27218
[44]	train-mlogloss:0.31615	eval-mlogloss:0.26595
[45]	train-mlogloss:0.30943	eval-mlogloss:0.25836
[46]	train-mlogloss:0.30415	eval-mlogloss:0.25260
[47]	train-mlogloss:0.29863	eval-mlogloss:0.24674
[48]	train-mlogloss:0.29390	eval-mlogloss:0.24133
[49]	train-mlogloss:0.28884	eval-mlogloss:0.23639
[50]	train-mlogloss:0.28446	eval-mlogloss:0.23127
[51]	train-mlogloss:0.27961	eval-mlogloss:0.22573
[52]	train-mlogloss:0.27551	eval-mlogloss:0.22100
[53]	train-mlogloss:0.27177	eval-mlogloss:0.21668
[54]	train-mlogloss:0.26780	eval-mlogloss:0.21249
[55]	train-mlogloss:0.26398	eval-mlogloss:0.20839
[56]	train-mlogloss:0.25960	eval-mlogloss:0.20342
[57]	train-mlogloss:0.25629	eval-mlogloss:0.19969
[58]	train-mlogloss:0.25284	eval-mlogloss:0.19610
[59]	train-mlogloss:0.25004	eval-mlogloss:0.19307
[60]	train-mlogloss:0.24892	eval-mlogloss:0.19195
[61]	train-mlogloss:0.24734	eval-mlogloss:0.19030
[62]	train-mlogloss:0.24433	eval-mlogloss:0.18696
[63]	train-mlogloss:0.24128	eval-mlogloss:0.18353
[64]	train-mlogloss:0.24006	eval-mlogloss:0.18159
[65]	train-mlogloss:0.23671	eval-mlogloss:0.17805
[66]	train-mlogloss:0.23530	eval-mlogloss:0.17637
[67]	train-mlogloss:0.23413	eval-mlogloss:0.17466
[68]	train-mlogloss:0.23330	eval-mlogloss:0.17365
[69]	train-mlogloss:0.23214	eval-mlogloss:0.17231
[70]	train-mlogloss:0.23166	eval-mlogloss:0.17176
[71]	train-mlogloss:0.22913	eval-mlogloss:0.16907
[72]	train-mlogloss:0.22782	eval-mlogloss:0.16758
[73]	train-mlogloss:0.22688	eval-mlogloss:0.16638
[74]	train-mlogloss:0.22584	eval-mlogloss:0.16498
[75]	train-mlogloss:0.22486	eval-mlogloss:0.16379
[76]	train-mlogloss:0.22393	eval-mlogloss:0.16258
[77]	train-mlogloss:0.22387	eval-mlogloss:0.16255
[78]	train-mlogloss:0.22378	eval-mlogloss:0.16245
[79]	train-mlogloss:0.22278	eval-mlogloss:0.16115
[80]	train-mlogloss:0.22150	eval-mlogloss:0.15971
[81]	train-mlogloss:0.22150	eval-mlogloss:0.15966
[82]	train-mlogloss:0.22148	eval-mlogloss:0.15966
[83]	train-mlogloss:0.22073	eval-mlogloss:0.15869
[84]	train-mlogloss:0.21979	eval-mlogloss:0.15773
[85]	train-mlogloss:0.21966	eval-mlogloss:0.15765
[86]	train-mlogloss:0.21922	eval-mlogloss:0.15686
[87]	train-mlogloss:0.21912	eval-mlogloss:0.15681
[88]	train-mlogloss:0.21753	eval-mlogloss:0.15533
[89]	train-mlogloss:0.21650	eval-mlogloss:0.15393
[90]	train-mlogloss:0.21576	eval-mlogloss:0.15313
[91]	train-mlogloss:0.21568	eval-mlogloss:0.15279
[92]	train-mlogloss:0.21557	eval-mlogloss:0.15271
[93]	train-mlogloss:0.21550	eval-mlogloss:0.15246
[94]	train-mlogloss:0.21546	eval-mlogloss:0.15227
[95]	train-mlogloss:0.21533	eval-mlogloss:0.15223
[96]	train-mlogloss:0.21525	eval-mlogloss:0.15215
[97]	train-mlogloss:0.21510	eval-mlogloss:0.15204
[98]	train-mlogloss:0.21413	eval-mlogloss:0.15089
[99]	train-mlogloss:0.21353	eval-mlogloss:0.15006
[100]	train-mlogloss:0.21346	eval-mlogloss:0.15001
[101]	train-mlogloss:0.21256	eval-mlogloss:0.14906
[102]	train-mlogloss:0.21176	eval-mlogloss:0.14767
[103]	train-mlogloss:0.21118	eval-mlogloss:0.14686
[104]	train-mlogloss:0.21109	eval-mlogloss:0.14681
[105]	train-mlogloss:0.21105	eval-mlogloss:0.14675
[106]	train-mlogloss:0.21019	eval-mlogloss:0.14557
[107]	train-mlogloss:0.21011	eval-mlogloss:0.14557
[108]	train-mlogloss:0.21000	eval-mlogloss:0.14547
[109]	train-mlogloss:0.20992	eval-mlogloss:0.14540
[110]	train-mlogloss:0.20985	eval-mlogloss:0.14541
[111]	train-mlogloss:0.20976	eval-mlogloss:0.14535
[112]	train-mlogloss:0.20882	eval-mlogloss:0.14432
[113]	train-mlogloss:0.20844	eval-mlogloss:0.14343
[114]	train-mlogloss:0.20838	eval-mlogloss:0.14310
[115]	train-mlogloss:0.20835	eval-mlogloss:0.14305
[116]	train-mlogloss:0.20823	eval-mlogloss:0.14296
[117]	train-mlogloss:0.20819	eval-mlogloss:0.14285
[118]	train-mlogloss:0.20817	eval-mlogloss:0.14287
[119]	train-mlogloss:0.20795	eval-mlogloss:0.14255
[120]	train-mlogloss:0.20791	eval-mlogloss:0.14251
[121]	train-mlogloss:0.20785	eval-mlogloss:0.14246
[122]	train-mlogloss:0.20771	eval-mlogloss:0.14236
[123]	train-mlogloss:0.20764	eval-mlogloss:0.14230
[124]	train-mlogloss:0.20695	eval-mlogloss:0.14130
[125]	train-mlogloss:0.20687	eval-mlogloss:0.14124
[126]	train-mlogloss:0.20681	eval-mlogloss:0.14102
[127]	train-mlogloss:0.20676	eval-mlogloss:0.14097
[128]	train-mlogloss:0.20678	eval-mlogloss:0.14101
[129]	train-mlogloss:0.20642	eval-mlogloss:0.14062
[130]	train-mlogloss:0.20634	eval-mlogloss:0.14060
[131]	train-mlogloss:0.20634	eval-mlogloss:0.14061
[132]	train-mlogloss:0.20548	eval-mlogloss:0.13974
[133]	train-mlogloss:0.20495	eval-mlogloss:0.13900
[134]	train-mlogloss:0.20494	eval-mlogloss:0.13899
[135]	train-mlogloss:0.20477	eval-mlogloss:0.13886
[136]	train-mlogloss:0.20478	eval-mlogloss:0.13889
[137]	train-mlogloss:0.20470	eval-mlogloss:0.13882
[138]	train-mlogloss:0.20464	eval-mlogloss:0.13873
[139]	train-mlogloss:0.20453	eval-mlogloss:0.13862
[140]	train-mlogloss:0.20444	eval-mlogloss:0.13849
[141]	train-mlogloss:0.20439	eval-mlogloss:0.13820
[142]	train-mlogloss:0.20433	eval-mlogloss:0.13820
[143]	train-mlogloss:0.20424	eval-mlogloss:0.13817
[144]	train-mlogloss:0.20414	eval-mlogloss:0.13813
[145]	train-mlogloss:0.20410	eval-mlogloss:0.13791
[146]	train-mlogloss:0.20406	eval-mlogloss:0.13787
[147]	train-mlogloss:0.20345	eval-mlogloss:0.13677
[148]	train-mlogloss:0.20343	eval-mlogloss:0.13677
[149]	train-mlogloss:0.20342	eval-mlogloss:0.13677
[150]	train-mlogloss:0.20339	eval-mlogloss:0.13678
[151]	train-mlogloss:0.20338	eval-mlogloss:0.13675
[152]	train-mlogloss:0.20330	eval-mlogloss:0.13669
[153]	train-mlogloss:0.20326	eval-mlogloss:0.13674
[154]	train-mlogloss:0.20314	eval-mlogloss:0.13652
[155]	train-mlogloss:0.20309	eval-mlogloss:0.13656
[156]	train-mlogloss:0.20299	eval-mlogloss:0.13647
[157]	train-mlogloss:0.20298	eval-mlogloss:0.13646
[158]	train-mlogloss:0.20291	eval-mlogloss:0.13617
[159]	train-mlogloss:0.20278	eval-mlogloss:0.13613
[160]	train-mlogloss:0.20267	eval-mlogloss:0.13608
[161]	train-mlogloss:0.20258	eval-mlogloss:0.13595
[162]	train-mlogloss:0.20256	eval-mlogloss:0.13596
[163]	train-mlogloss:0.20257	eval-mlogloss:0.13600
[164]	train-mlogloss:0.20255	eval-mlogloss:0.13583
[165]	train-mlogloss:0.20249	eval-mlogloss:0.13579
[166]	train-mlogloss:0.20171	eval-mlogloss:0.13465
[167]	train-mlogloss:0.20169	eval-mlogloss:0.13464
[168]	train-mlogloss:0.20169	eval-mlogloss:0.13464
[169]	train-mlogloss:0.20155	eval-mlogloss:0.13452
[170]	train-mlogloss:0.20152	eval-mlogloss:0.13444
[171]	train-mlogloss:0.20149	eval-mlogloss:0.13429
[172]	train-mlogloss:0.20148	eval-mlogloss:0.13424
[173]	train-mlogloss:0.20138	eval-mlogloss:0.13421
[174]	train-mlogloss:0.20133	eval-mlogloss:0.13419
[175]	train-mlogloss:0.20127	eval-mlogloss:0.13416
[176]	train-mlogloss:0.20122	eval-mlogloss:0.13408
[177]	train-mlogloss:0.20115	eval-mlogloss:0.13402
[178]	train-mlogloss:0.20110	eval-mlogloss:0.13398
[179]	train-mlogloss:0.20110	eval-mlogloss:0.13402
[180]	train-mlogloss:0.20105	eval-mlogloss:0.13364
[181]	train-mlogloss:0.20103	eval-mlogloss:0.13360
[182]	train-mlogloss:0.20099	eval-mlogloss:0.13363
[183]	train-mlogloss:0.20094	eval-mlogloss:0.13340
[184]	train-mlogloss:0.20090	eval-mlogloss:0.13315
[185]	train-mlogloss:0.20090	eval-mlogloss:0.13319
[186]	train-mlogloss:0.20082	eval-mlogloss:0.13311
[187]	train-mlogloss:0.20082	eval-mlogloss:0.13310
[188]	train-mlogloss:0.20083	eval-mlogloss:0.13313
[189]	train-mlogloss:0.20079	eval-mlogloss:0.13313
[190]	train-mlogloss:0.20072	eval-mlogloss:0.13313
[191]	train-mlogloss:0.20069	eval-mlogloss:0.13297
[192]	train-mlogloss:0.20067	eval-mlogloss:0.13294
[193]	train-mlogloss:0.20060	eval-mlogloss:0.13289
[194]	train-mlogloss:0.20051	eval-mlogloss:0.13281
[195]	train-mlogloss:0.20052	eval-mlogloss:0.13280
[196]	train-mlogloss:0.20045	eval-mlogloss:0.13277
[197]	train-mlogloss:0.20044	eval-mlogloss:0.13275
[198]	train-mlogloss:0.20040	eval-mlogloss:0.13280
[199]	train-mlogloss:0.20038	eval-mlogloss:0.13274
[200]	train-mlogloss:0.20034	eval-mlogloss:0.13272
[201]	train-mlogloss:0.20030	eval-mlogloss:0.13242
[202]	train-mlogloss:0.20021	eval-mlogloss:0.13234
[203]	train-mlogloss:0.20017	eval-mlogloss:0.13212
[204]	train-mlogloss:0.20009	eval-mlogloss:0.13209
[205]	train-mlogloss:0.20006	eval-mlogloss:0.13185
[206]	train-mlogloss:0.20001	eval-mlogloss:0.13181
[207]	train-mlogloss:0.19996	eval-mlogloss:0.13178
[208]	train-mlogloss:0.19990	eval-mlogloss:0.13178
[209]	train-mlogloss:0.19928	eval-mlogloss:0.13094
[210]	train-mlogloss:0.19924	eval-mlogloss:0.13065
[211]	train-mlogloss:0.19920	eval-mlogloss:0.13061
[212]	train-mlogloss:0.19912	eval-mlogloss:0.13058
[213]	train-mlogloss:0.19910	eval-mlogloss:0.13040
[214]	train-mlogloss:0.19910	eval-mlogloss:0.13040
[215]	train-mlogloss:0.19899	eval-mlogloss:0.13037
[216]	train-mlogloss:0.19834	eval-mlogloss:0.12965
[217]	train-mlogloss:0.19829	eval-mlogloss:0.12965
[218]	train-mlogloss:0.19776	eval-mlogloss:0.12891
[219]	train-mlogloss:0.19777	eval-mlogloss:0.12890
[220]	train-mlogloss:0.19768	eval-mlogloss:0.12887
[221]	train-mlogloss:0.19767	eval-mlogloss:0.12887
[222]	train-mlogloss:0.19765	eval-mlogloss:0.12891
[223]	train-mlogloss:0.19760	eval-mlogloss:0.12890
[224]	train-mlogloss:0.19754	eval-mlogloss:0.12886
[225]	train-mlogloss:0.19753	eval-mlogloss:0.12886
[226]	train-mlogloss:0.19749	eval-mlogloss:0.12882
[227]	train-mlogloss:0.19749	eval-mlogloss:0.12884
[228]	train-mlogloss:0.19745	eval-mlogloss:0.12883
[229]	train-mlogloss:0.19738	eval-mlogloss:0.12886
[230]	train-mlogloss:0.19733	eval-mlogloss:0.12886
[231]	train-mlogloss:0.19732	eval-mlogloss:0.12883
[232]	train-mlogloss:0.19729	eval-mlogloss:0.12883
[233]	train-mlogloss:0.19725	eval-mlogloss:0.12879
[234]	train-mlogloss:0.19727	eval-mlogloss:0.12886
[235]	train-mlogloss:0.19725	eval-mlogloss:0.12879
[236]	train-mlogloss:0.19719	eval-mlogloss:0.12880
[237]	train-mlogloss:0.19720	eval-mlogloss:0.12882
[238]	train-mlogloss:0.19710	eval-mlogloss:0.12881
[239]	train-mlogloss:0.19709	eval-mlogloss:0.12880
[240]	train-mlogloss:0.19703	eval-mlogloss:0.12881
[241]	train-mlogloss:0.19700	eval-mlogloss:0.12883
[242]	train-mlogloss:0.19695	eval-mlogloss:0.12880
[243]	train-mlogloss:0.19695	eval-mlogloss:0.12877
[244]	train-mlogloss:0.19694	eval-mlogloss:0.12875
[245]	train-mlogloss:0.19694	eval-mlogloss:0.12874
[246]	train-mlogloss:0.19690	eval-mlogloss:0.12863
[247]	train-mlogloss:0.19691	eval-mlogloss:0.12863
[248]	train-mlogloss:0.19691	eval-mlogloss:0.12864
[249]	train-mlogloss:0.19689	eval-mlogloss:0.12858
[250]	train-mlogloss:0.19686	eval-mlogloss:0.12858
[251]	train-mlogloss:0.19682	eval-mlogloss:0.12856
[252]	train-mlogloss:0.19678	eval-mlogloss:0.12858
[253]	train-mlogloss:0.19678	eval-mlogloss:0.12858
[254]	train-mlogloss:0.19674	eval-mlogloss:0.12859
[255]	train-mlogloss:0.19670	eval-mlogloss:0.12858
[256]	train-mlogloss:0.19670	eval-mlogloss:0.12857
[257]	train-mlogloss:0.19664	eval-mlogloss:0.12851
[258]	train-mlogloss:0.19664	eval-mlogloss:0.12849
[259]	train-mlogloss:0.19664	eval-mlogloss:0.12851
[260]	train-mlogloss:0.19659	eval-mlogloss:0.12847
[261]	train-mlogloss:0.19657	eval-mlogloss:0.12849
[262]	train-mlogloss:0.19653	eval-mlogloss:0.12826
[263]	train-mlogloss:0.19652	eval-mlogloss:0.12825
[264]	train-mlogloss:0.19646	eval-mlogloss:0.12819
[265]	train-mlogloss:0.19639	eval-mlogloss:0.12818
[266]	train-mlogloss:0.19635	eval-mlogloss:0.12788
[267]	train-mlogloss:0.19627	eval-mlogloss:0.12782
[268]	train-mlogloss:0.19614	eval-mlogloss:0.12763
[269]	train-mlogloss:0.19609	eval-mlogloss:0.12760
[270]	train-mlogloss:0.19607	eval-mlogloss:0.12759
[271]	train-mlogloss:0.19608	eval-mlogloss:0.12761
[272]	train-mlogloss:0.19604	eval-mlogloss:0.12760
[273]	train-mlogloss:0.19601	eval-mlogloss:0.12755
[274]	train-mlogloss:0.19601	eval-mlogloss:0.12753
[275]	train-mlogloss:0.19594	eval-mlogloss:0.12753
[276]	train-mlogloss:0.19595	eval-mlogloss:0.12752
[277]	train-mlogloss:0.19590	eval-mlogloss:0.12751
[278]	train-mlogloss:0.19584	eval-mlogloss:0.12746
[279]	train-mlogloss:0.19581	eval-mlogloss:0.12742
[280]	train-mlogloss:0.19580	eval-mlogloss:0.12738
[281]	train-mlogloss:0.19576	eval-mlogloss:0.12739
[282]	train-mlogloss:0.19572	eval-mlogloss:0.12741
[283]	train-mlogloss:0.19568	eval-mlogloss:0.12716
[284]	train-mlogloss:0.19568	eval-mlogloss:0.12718
[285]	train-mlogloss:0.19568	eval-mlogloss:0.12717
[286]	train-mlogloss:0.19563	eval-mlogloss:0.12717
[287]	train-mlogloss:0.19533	eval-mlogloss:0.12671
[288]	train-mlogloss:0.19533	eval-mlogloss:0.12671
[289]	train-mlogloss:0.19464	eval-mlogloss:0.12596
[290]	train-mlogloss:0.19460	eval-mlogloss:0.12593
[291]	train-mlogloss:0.19460	eval-mlogloss:0.12595
[292]	train-mlogloss:0.19460	eval-mlogloss:0.12597
[293]	train-mlogloss:0.19458	eval-mlogloss:0.12597
[294]	train-mlogloss:0.19455	eval-mlogloss:0.12597
[295]	train-mlogloss:0.19451	eval-mlogloss:0.12591
[296]	train-mlogloss:0.19451	eval-mlogloss:0.12595
[297]	train-mlogloss:0.19451	eval-mlogloss:0.12597
[298]	train-mlogloss:0.19447	eval-mlogloss:0.12594
[299]	train-mlogloss:0.19446	eval-mlogloss:0.12593

[I 2026-03-02 05:11:18,527] Trial 11 finished with value: 1.0 and parameters: {'lambda': 3.967615441177637e-05, 'alpha': 0.017890177902533277, 'eta': 0.031162473676205685, 'gamma': 0.0012652879748173145, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.667190838421931, 'colsample_bytree': 0.8336746791903964}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.07768	eval-mlogloss:1.07814
[1]	train-mlogloss:1.05729	eval-mlogloss:1.05725
[2]	train-mlogloss:1.03722	eval-mlogloss:1.03630
[3]	train-mlogloss:1.01732	eval-mlogloss:1.01561
[4]	train-mlogloss:0.99865	eval-mlogloss:0.99646
[5]	train-mlogloss:0.97990	eval-mlogloss:0.97657
[6]	train-mlogloss:0.96230	eval-mlogloss:0.95856
[7]	train-mlogloss:0.94534	eval-mlogloss:0.94066
[8]	train-mlogloss:0.92860	eval-mlogloss:0.92311
[9]	train-mlogloss:0.91214	eval-mlogloss:0.90557
[10]	train-mlogloss:0.89605	eval-mlogloss:0.88896
[11]	train-mlogloss:0.88051	eval-mlogloss:0.87271
[12]	train-mlogloss:0.86557	eval-mlogloss:0.85721
[13]	train-mlogloss:0.85066	eval-mlogloss:0.84153
[14]	train-mlogloss:0.83636	eval-mlogloss:0.82666
[15]	train-mlogloss:0.82203	eval-mlogloss:0.81157
[16]	train-mlogloss:0.80831	eval-mlogloss:0.79698
[17]	train-mlogloss:0.79484	eval-mlogloss:0.78223
[18]	train-mlogloss:0.78283	eval-mlogloss:0.77024
[19]	train-mlogloss:0.76993	eval-mlogloss:0.75657
[20]	train-mlogloss:0.75713	eval-mlogloss:0.74298
[21]	train-mlogloss:0.74598	eval-mlogloss:0.73063
[22]	train-mlogloss:0.73371	eval-mlogloss:0.71785
[23]	train-mlogloss:0.72173	eval-mlogloss:0.70544
[24]	train-mlogloss:0.71020	eval-mlogloss:0.69299
[25]	train-mlogloss:0.69910	eval-mlogloss:0.68093
[26]	train-mlogloss:0.68815	eval-mlogloss:0.66900
[27]	train-mlogloss:0.67756	eval-mlogloss:0.65798
[28]	train-mlogloss:0.66679	eval-mlogloss:0.64650
[29]	train-mlogloss:0.65617	eval-mlogloss:0.63511
[30]	train-mlogloss:0.64612	eval-mlogloss:0.62482
[31]	train-mlogloss:0.63613	eval-mlogloss:0.61393
[32]	train-mlogloss:0.62637	eval-mlogloss:0.60329
[33]	train-mlogloss:0.61802	eval-mlogloss:0.59388
[34]	train-mlogloss:0.60862	eval-mlogloss:0.58412
[35]	train-mlogloss:0.59965	eval-mlogloss:0.57419
[36]	train-mlogloss:0.59047	eval-mlogloss:0.56475
[37]	train-mlogloss:0.58175	eval-mlogloss:0.55565
[38]	train-mlogloss:0.57338	eval-mlogloss:0.54690
[39]	train-mlogloss:0.56479	eval-mlogloss:0.53818
[40]	train-mlogloss:0.55665	eval-mlogloss:0.52988
[41]	train-mlogloss:0.54857	eval-mlogloss:0.52120
[42]	train-mlogloss:0.54082	eval-mlogloss:0.51294
[43]	train-mlogloss:0.53301	eval-mlogloss:0.50463
[44]	train-mlogloss:0.52519	eval-mlogloss:0.49634
[45]	train-mlogloss:0.51759	eval-mlogloss:0.48831
[46]	train-mlogloss:0.50991	eval-mlogloss:0.48041
[47]	train-mlogloss:0.50273	eval-mlogloss:0.47311
[48]	train-mlogloss:0.49538	eval-mlogloss:0.46519
[49]	train-mlogloss:0.48843	eval-mlogloss:0.45781
[50]	train-mlogloss:0.48158	eval-mlogloss:0.45064
[51]	train-mlogloss:0.47499	eval-mlogloss:0.44346
[52]	train-mlogloss:0.46853	eval-mlogloss:0.43634
[53]	train-mlogloss:0.46220	eval-mlogloss:0.42933
[54]	train-mlogloss:0.45573	eval-mlogloss:0.42261
[55]	train-mlogloss:0.44938	eval-mlogloss:0.41592
[56]	train-mlogloss:0.44345	eval-mlogloss:0.40954
[57]	train-mlogloss:0.43762	eval-mlogloss:0.40306
[58]	train-mlogloss:0.43170	eval-mlogloss:0.39685
[59]	train-mlogloss:0.42612	eval-mlogloss:0.39129
[60]	train-mlogloss:0.42076	eval-mlogloss:0.38594
[61]	train-mlogloss:0.41520	eval-mlogloss:0.38039
[62]	train-mlogloss:0.40985	eval-mlogloss:0.37489
[63]	train-mlogloss:0.40454	eval-mlogloss:0.36926
[64]	train-mlogloss:0.39929	eval-mlogloss:0.36368
[65]	train-mlogloss:0.39394	eval-mlogloss:0.35790
[66]	train-mlogloss:0.38870	eval-mlogloss:0.35248
[67]	train-mlogloss:0.38360	eval-mlogloss:0.34686
[68]	train-mlogloss:0.37906	eval-mlogloss:0.34216
[69]	train-mlogloss:0.37439	eval-mlogloss:0.33763
[70]	train-mlogloss:0.36957	eval-mlogloss:0.33238
[71]	train-mlogloss:0.36498	eval-mlogloss:0.32742
[72]	train-mlogloss:0.36052	eval-mlogloss:0.32282
[73]	train-mlogloss:0.35591	eval-mlogloss:0.31785
[74]	train-mlogloss:0.35150	eval-mlogloss:0.31333
[75]	train-mlogloss:0.34718	eval-mlogloss:0.30875
[76]	train-mlogloss:0.34286	eval-mlogloss:0.30391
[77]	train-mlogloss:0.33878	eval-mlogloss:0.29940
[78]	train-mlogloss:0.33460	eval-mlogloss:0.29463
[79]	train-mlogloss:0.33060	eval-mlogloss:0.29045
[80]	train-mlogloss:0.32686	eval-mlogloss:0.28637
[81]	train-mlogloss:0.32276	eval-mlogloss:0.28190
[82]	train-mlogloss:0.31914	eval-mlogloss:0.27769
[83]	train-mlogloss:0.31518	eval-mlogloss:0.27351
[84]	train-mlogloss:0.31151	eval-mlogloss:0.26955
[85]	train-mlogloss:0.30782	eval-mlogloss:0.26547
[86]	train-mlogloss:0.30422	eval-mlogloss:0.26144
[87]	train-mlogloss:0.30049	eval-mlogloss:0.25739
[88]	train-mlogloss:0.29689	eval-mlogloss:0.25366
[89]	train-mlogloss:0.29333	eval-mlogloss:0.25004
[90]	train-mlogloss:0.29027	eval-mlogloss:0.24683
[91]	train-mlogloss:0.28717	eval-mlogloss:0.24358
[92]	train-mlogloss:0.28385	eval-mlogloss:0.24004
[93]	train-mlogloss:0.28065	eval-mlogloss:0.23657
[94]	train-mlogloss:0.27766	eval-mlogloss:0.23338
[95]	train-mlogloss:0.27468	eval-mlogloss:0.23004
[96]	train-mlogloss:0.27188	eval-mlogloss:0.22687
[97]	train-mlogloss:0.26913	eval-mlogloss:0.22380
[98]	train-mlogloss:0.26625	eval-mlogloss:0.22062
[99]	train-mlogloss:0.26351	eval-mlogloss:0.21791
[100]	train-mlogloss:0.26077	eval-mlogloss:0.21490
[101]	train-mlogloss:0.25832	eval-mlogloss:0.21214
[102]	train-mlogloss:0.25553	eval-mlogloss:0.20914
[103]	train-mlogloss:0.25314	eval-mlogloss:0.20637
[104]	train-mlogloss:0.25045	eval-mlogloss:0.20329
[105]	train-mlogloss:0.24830	eval-mlogloss:0.20083
[106]	train-mlogloss:0.24595	eval-mlogloss:0.19858
[107]	train-mlogloss:0.24379	eval-mlogloss:0.19595
[108]	train-mlogloss:0.24157	eval-mlogloss:0.19338
[109]	train-mlogloss:0.23924	eval-mlogloss:0.19067
[110]	train-mlogloss:0.23705	eval-mlogloss:0.18829
[111]	train-mlogloss:0.23533	eval-mlogloss:0.18635
[112]	train-mlogloss:0.23305	eval-mlogloss:0.18384
[113]	train-mlogloss:0.23153	eval-mlogloss:0.18194
[114]	train-mlogloss:0.22961	eval-mlogloss:0.17983
[115]	train-mlogloss:0.22769	eval-mlogloss:0.17762
[116]	train-mlogloss:0.22569	eval-mlogloss:0.17518
[117]	train-mlogloss:0.22357	eval-mlogloss:0.17272
[118]	train-mlogloss:0.22199	eval-mlogloss:0.17116
[119]	train-mlogloss:0.21994	eval-mlogloss:0.16894
[120]	train-mlogloss:0.21805	eval-mlogloss:0.16681
[121]	train-mlogloss:0.21601	eval-mlogloss:0.16451
[122]	train-mlogloss:0.21408	eval-mlogloss:0.16222
[123]	train-mlogloss:0.21261	eval-mlogloss:0.16087
[124]	train-mlogloss:0.21084	eval-mlogloss:0.15901
[125]	train-mlogloss:0.20912	eval-mlogloss:0.15684
[126]	train-mlogloss:0.20825	eval-mlogloss:0.15559
[127]	train-mlogloss:0.20656	eval-mlogloss:0.15364
[128]	train-mlogloss:0.20490	eval-mlogloss:0.15158
[129]	train-mlogloss:0.20413	eval-mlogloss:0.15059
[130]	train-mlogloss:0.20270	eval-mlogloss:0.14890
[131]	train-mlogloss:0.20145	eval-mlogloss:0.14759
[132]	train-mlogloss:0.19996	eval-mlogloss:0.14596
[133]	train-mlogloss:0.19880	eval-mlogloss:0.14456
[134]	train-mlogloss:0.19760	eval-mlogloss:0.14313
[135]	train-mlogloss:0.19636	eval-mlogloss:0.14175
[136]	train-mlogloss:0.19517	eval-mlogloss:0.14045
[137]	train-mlogloss:0.19397	eval-mlogloss:0.13918
[138]	train-mlogloss:0.19268	eval-mlogloss:0.13762
[139]	train-mlogloss:0.19125	eval-mlogloss:0.13606
[140]	train-mlogloss:0.19004	eval-mlogloss:0.13478
[141]	train-mlogloss:0.18899	eval-mlogloss:0.13360
[142]	train-mlogloss:0.18795	eval-mlogloss:0.13240
[143]	train-mlogloss:0.18681	eval-mlogloss:0.13122
[144]	train-mlogloss:0.18564	eval-mlogloss:0.12997
[145]	train-mlogloss:0.18452	eval-mlogloss:0.12877
[146]	train-mlogloss:0.18348	eval-mlogloss:0.12749
[147]	train-mlogloss:0.18254	eval-mlogloss:0.12635
[148]	train-mlogloss:0.18151	eval-mlogloss:0.12530
[149]	train-mlogloss:0.18049	eval-mlogloss:0.12429
[150]	train-mlogloss:0.17953	eval-mlogloss:0.12327
[151]	train-mlogloss:0.17864	eval-mlogloss:0.12231
[152]	train-mlogloss:0.17827	eval-mlogloss:0.12184
[153]	train-mlogloss:0.17726	eval-mlogloss:0.12076
[154]	train-mlogloss:0.17620	eval-mlogloss:0.11959
[155]	train-mlogloss:0.17574	eval-mlogloss:0.11892
[156]	train-mlogloss:0.17538	eval-mlogloss:0.11828
[157]	train-mlogloss:0.17504	eval-mlogloss:0.11762
[158]	train-mlogloss:0.17460	eval-mlogloss:0.11706
[159]	train-mlogloss:0.17360	eval-mlogloss:0.11595
[160]	train-mlogloss:0.17263	eval-mlogloss:0.11480
[161]	train-mlogloss:0.17228	eval-mlogloss:0.11427
[162]	train-mlogloss:0.17192	eval-mlogloss:0.11379
[163]	train-mlogloss:0.17164	eval-mlogloss:0.11338
[164]	train-mlogloss:0.17083	eval-mlogloss:0.11248
[165]	train-mlogloss:0.17049	eval-mlogloss:0.11199
[166]	train-mlogloss:0.17011	eval-mlogloss:0.11144
[167]	train-mlogloss:0.16968	eval-mlogloss:0.11082
[168]	train-mlogloss:0.16898	eval-mlogloss:0.11038
[169]	train-mlogloss:0.16860	eval-mlogloss:0.10984
[170]	train-mlogloss:0.16835	eval-mlogloss:0.10946
[171]	train-mlogloss:0.16800	eval-mlogloss:0.10893
[172]	train-mlogloss:0.16774	eval-mlogloss:0.10856
[173]	train-mlogloss:0.16751	eval-mlogloss:0.10825
[174]	train-mlogloss:0.16715	eval-mlogloss:0.10775
[175]	train-mlogloss:0.16678	eval-mlogloss:0.10735
[176]	train-mlogloss:0.16644	eval-mlogloss:0.10680
[177]	train-mlogloss:0.16574	eval-mlogloss:0.10602
[178]	train-mlogloss:0.16547	eval-mlogloss:0.10567
[179]	train-mlogloss:0.16475	eval-mlogloss:0.10486
[180]	train-mlogloss:0.16475	eval-mlogloss:0.10474
[181]	train-mlogloss:0.16432	eval-mlogloss:0.10413
[182]	train-mlogloss:0.16404	eval-mlogloss:0.10369
[183]	train-mlogloss:0.16382	eval-mlogloss:0.10338
[184]	train-mlogloss:0.16356	eval-mlogloss:0.10300
[185]	train-mlogloss:0.16316	eval-mlogloss:0.10240
[186]	train-mlogloss:0.16289	eval-mlogloss:0.10202
[187]	train-mlogloss:0.16262	eval-mlogloss:0.10162
[188]	train-mlogloss:0.16257	eval-mlogloss:0.10159
[189]	train-mlogloss:0.16224	eval-mlogloss:0.10110
[190]	train-mlogloss:0.16189	eval-mlogloss:0.10062
[191]	train-mlogloss:0.16169	eval-mlogloss:0.10028
[192]	train-mlogloss:0.16141	eval-mlogloss:0.09989
[193]	train-mlogloss:0.16113	eval-mlogloss:0.09950
[194]	train-mlogloss:0.16086	eval-mlogloss:0.09912
[195]	train-mlogloss:0.16066	eval-mlogloss:0.09887
[196]	train-mlogloss:0.16041	eval-mlogloss:0.09857
[197]	train-mlogloss:0.16010	eval-mlogloss:0.09822
[198]	train-mlogloss:0.16007	eval-mlogloss:0.09818
[199]	train-mlogloss:0.15979	eval-mlogloss:0.09787
[200]	train-mlogloss:0.15966	eval-mlogloss:0.09791
[201]	train-mlogloss:0.15943	eval-mlogloss:0.09744
[202]	train-mlogloss:0.15937	eval-mlogloss:0.09739
[203]	train-mlogloss:0.15917	eval-mlogloss:0.09713
[204]	train-mlogloss:0.15893	eval-mlogloss:0.09682
[205]	train-mlogloss:0.15881	eval-mlogloss:0.09664
[206]	train-mlogloss:0.15874	eval-mlogloss:0.09650
[207]	train-mlogloss:0.15866	eval-mlogloss:0.09650
[208]	train-mlogloss:0.15842	eval-mlogloss:0.09627
[209]	train-mlogloss:0.15820	eval-mlogloss:0.09591
[210]	train-mlogloss:0.15814	eval-mlogloss:0.09584
[211]	train-mlogloss:0.15793	eval-mlogloss:0.09562
[212]	train-mlogloss:0.15772	eval-mlogloss:0.09533
[213]	train-mlogloss:0.15771	eval-mlogloss:0.09525
[214]	train-mlogloss:0.15752	eval-mlogloss:0.09510
[215]	train-mlogloss:0.15725	eval-mlogloss:0.09479
[216]	train-mlogloss:0.15702	eval-mlogloss:0.09437
[217]	train-mlogloss:0.15698	eval-mlogloss:0.09436
[218]	train-mlogloss:0.15680	eval-mlogloss:0.09405
[219]	train-mlogloss:0.15681	eval-mlogloss:0.09410
[220]	train-mlogloss:0.15669	eval-mlogloss:0.09412
[221]	train-mlogloss:0.15650	eval-mlogloss:0.09414
[222]	train-mlogloss:0.15631	eval-mlogloss:0.09387
[223]	train-mlogloss:0.15628	eval-mlogloss:0.09382
[224]	train-mlogloss:0.15597	eval-mlogloss:0.09348
[225]	train-mlogloss:0.15569	eval-mlogloss:0.09312
[226]	train-mlogloss:0.15543	eval-mlogloss:0.09277
[227]	train-mlogloss:0.15543	eval-mlogloss:0.09279
[228]	train-mlogloss:0.15535	eval-mlogloss:0.09279
[229]	train-mlogloss:0.15521	eval-mlogloss:0.09268
[230]	train-mlogloss:0.15495	eval-mlogloss:0.09234
[231]	train-mlogloss:0.15493	eval-mlogloss:0.09233
[232]	train-mlogloss:0.15492	eval-mlogloss:0.09226
[233]	train-mlogloss:0.15487	eval-mlogloss:0.09222
[234]	train-mlogloss:0.15474	eval-mlogloss:0.09226
[235]	train-mlogloss:0.15459	eval-mlogloss:0.09203
[236]	train-mlogloss:0.15455	eval-mlogloss:0.09202
[237]	train-mlogloss:0.15442	eval-mlogloss:0.09204
[238]	train-mlogloss:0.15434	eval-mlogloss:0.09201
[239]	train-mlogloss:0.15433	eval-mlogloss:0.09200
[240]	train-mlogloss:0.15416	eval-mlogloss:0.09204
[241]	train-mlogloss:0.15397	eval-mlogloss:0.09184
[242]	train-mlogloss:0.15378	eval-mlogloss:0.09160
[243]	train-mlogloss:0.15378	eval-mlogloss:0.09159
[244]	train-mlogloss:0.15358	eval-mlogloss:0.09132
[245]	train-mlogloss:0.15357	eval-mlogloss:0.09129
[246]	train-mlogloss:0.15355	eval-mlogloss:0.09126
[247]	train-mlogloss:0.15346	eval-mlogloss:0.09127
[248]	train-mlogloss:0.15337	eval-mlogloss:0.09118
[249]	train-mlogloss:0.15326	eval-mlogloss:0.09101
[250]	train-mlogloss:0.15299	eval-mlogloss:0.09062
[251]	train-mlogloss:0.15296	eval-mlogloss:0.09046
[252]	train-mlogloss:0.15276	eval-mlogloss:0.09010
[253]	train-mlogloss:0.15271	eval-mlogloss:0.09009
[254]	train-mlogloss:0.15260	eval-mlogloss:0.08997
[255]	train-mlogloss:0.15238	eval-mlogloss:0.08968

[I 2026-03-02 05:11:21,269] Trial 12 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:0.99692	eval-mlogloss:0.99188

[I 2026-03-02 05:11:21,310] Trial 13 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00906	eval-mlogloss:1.00309

[I 2026-03-02 05:11:21,349] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.83998	eval-mlogloss:0.81987

[I 2026-03-02 05:11:21,402] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03401	eval-mlogloss:1.04109

[I 2026-03-02 05:11:21,445] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88549	eval-mlogloss:0.86822

[I 2026-03-02 05:11:21,505] Trial 17 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92997	eval-mlogloss:0.91712

[I 2026-03-02 05:11:21,539] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97015	eval-mlogloss:0.96078

[I 2026-03-02 05:11:21,579] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97884	eval-mlogloss:0.96329

[I 2026-03-02 05:11:21,616] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08540	eval-mlogloss:1.08637
[1]	train-mlogloss:1.07273	eval-mlogloss:1.07341
[2]	train-mlogloss:1.06016	eval-mlogloss:1.06029
[3]	train-mlogloss:1.04733	eval-mlogloss:1.04706
[4]	train-mlogloss:1.03527	eval-mlogloss:1.03455
[5]	train-mlogloss:1.02294	eval-mlogloss:1.02127
[6]	train-mlogloss:1.01117	eval-mlogloss:1.00891
[7]	train-mlogloss:0.99991	eval-mlogloss:0.99699
[8]	train-mlogloss:0.98871	eval-mlogloss:0.98514
[9]	train-mlogloss:0.97748	eval-mlogloss:0.97313
[10]	train-mlogloss:0.96645	eval-mlogloss:0.96179
[11]	train-mlogloss:0.95560	eval-mlogloss:0.95045
[12]	train-mlogloss:0.94521	eval-mlogloss:0.93975
[13]	train-mlogloss:0.93474	eval-mlogloss:0.92869
[14]	train-mlogloss:0.92448	eval-mlogloss:0.91795
[15]	train-mlogloss:0.91415	eval-mlogloss:0.90702
[16]	train-mlogloss:0.90416	eval-mlogloss:0.89639
[17]	train-mlogloss:0.89451	eval-mlogloss:0.88601
[18]	train-mlogloss:0.88582	eval-mlogloss:0.87737
[19]	train-mlogloss:0.87638	eval-mlogloss:0.86749
[20]	train-mlogloss:0.86683	eval-mlogloss:0.85725
[21]	train-mlogloss:0.85873	eval-mlogloss:0.84862
[22]	train-mlogloss:0.84950	eval-mlogloss:0.83905
[23]	train-mlogloss:0.84033	eval-mlogloss:0.82939
[24]	train-mlogloss:0.83223	eval-mlogloss:0.82094
[25]	train-mlogloss:0.82354	eval-mlogloss:0.81158
[26]	train-mlogloss:0.81508	eval-mlogloss:0.80263
[27]	train-mlogloss:0.80671	eval-mlogloss:0.79395
[28]	train-mlogloss:0.79828	eval-mlogloss:0.78514
[29]	train-mlogloss:0.78990	eval-mlogloss:0.77606
[30]	train-mlogloss:0.78188	eval-mlogloss:0.76774
[31]	train-mlogloss:0.77379	eval-mlogloss:0.75896
[32]	train-mlogloss:0.76585	eval-mlogloss:0.75030
[33]	train-mlogloss:0.75966	eval-mlogloss:0.74330
[34]	train-mlogloss:0.75195	eval-mlogloss:0.73528
[35]	train-mlogloss:0.74456	eval-mlogloss:0.72733
[36]	train-mlogloss:0.73680	eval-mlogloss:0.71922
[37]	train-mlogloss:0.72951	eval-mlogloss:0.71162
[38]	train-mlogloss:0.72245	eval-mlogloss:0.70421
[39]	train-mlogloss:0.71511	eval-mlogloss:0.69649
[40]	train-mlogloss:0.70813	eval-mlogloss:0.68905
[41]	train-mlogloss:0.70111	eval-mlogloss:0.68145
[42]	train-mlogloss:0.69440	eval-mlogloss:0.67440
[43]	train-mlogloss:0.68749	eval-mlogloss:0.66701
[44]	train-mlogloss:0.68068	eval-mlogloss:0.65988
[45]	train-mlogloss:0.67395	eval-mlogloss:0.65267
[46]	train-mlogloss:0.66727	eval-mlogloss:0.64571
[47]	train-mlogloss:0.66083	eval-mlogloss:0.63911
[48]	train-mlogloss:0.65424	eval-mlogloss:0.63193
[49]	train-mlogloss:0.64808	eval-mlogloss:0.62540
[50]	train-mlogloss:0.64194	eval-mlogloss:0.61874
[51]	train-mlogloss:0.63589	eval-mlogloss:0.61210
[52]	train-mlogloss:0.62986	eval-mlogloss:0.60554
[53]	train-mlogloss:0.62403	eval-mlogloss:0.59906
[54]	train-mlogloss:0.61803	eval-mlogloss:0.59269
[55]	train-mlogloss:0.61209	eval-mlogloss:0.58649
[56]	train-mlogloss:0.60639	eval-mlogloss:0.58046
[57]	train-mlogloss:0.60087	eval-mlogloss:0.57440
[58]	train-mlogloss:0.59539	eval-mlogloss:0.56861
[59]	train-mlogloss:0.58994	eval-mlogloss:0.56292
[60]	train-mlogloss:0.58475	eval-mlogloss:0.55755
[61]	train-mlogloss:0.57939	eval-mlogloss:0.55174
[62]	train-mlogloss:0.57407	eval-mlogloss:0.54608
[63]	train-mlogloss:0.56891	eval-mlogloss:0.54054
[64]	train-mlogloss:0.56369	eval-mlogloss:0.53493
[65]	train-mlogloss:0.55835	eval-mlogloss:0.52931
[66]	train-mlogloss:0.55322	eval-mlogloss:0.52374
[67]	train-mlogloss:0.54811	eval-mlogloss:0.51829
[68]	train-mlogloss:0.54342	eval-mlogloss:0.51319
[69]	train-mlogloss:0.53862	eval-mlogloss:0.50797
[70]	train-mlogloss:0.53375	eval-mlogloss:0.50266
[71]	train-mlogloss:0.52926	eval-mlogloss:0.49775
[72]	train-mlogloss:0.52469	eval-mlogloss:0.49276
[73]	train-mlogloss:0.51993	eval-mlogloss:0.48785
[74]	train-mlogloss:0.51538	eval-mlogloss:0.48293
[75]	train-mlogloss:0.51086	eval-mlogloss:0.47824
[76]	train-mlogloss:0.50627	eval-mlogloss:0.47306
[77]	train-mlogloss:0.50189	eval-mlogloss:0.46833
[78]	train-mlogloss:0.49738	eval-mlogloss:0.46338
[79]	train-mlogloss:0.49309	eval-mlogloss:0.45885
[80]	train-mlogloss:0.48909	eval-mlogloss:0.45458
[81]	train-mlogloss:0.48465	eval-mlogloss:0.44987
[82]	train-mlogloss:0.48072	eval-mlogloss:0.44529
[83]	train-mlogloss:0.47652	eval-mlogloss:0.44068
[84]	train-mlogloss:0.47247	eval-mlogloss:0.43631
[85]	train-mlogloss:0.46839	eval-mlogloss:0.43183
[86]	train-mlogloss:0.46443	eval-mlogloss:0.42746
[87]	train-mlogloss:0.46035	eval-mlogloss:0.42315
[88]	train-mlogloss:0.45630	eval-mlogloss:0.41895
[89]	train-mlogloss:0.45239	eval-mlogloss:0.41465
[90]	train-mlogloss:0.44886	eval-mlogloss:0.41079
[91]	train-mlogloss:0.44506	eval-mlogloss:0.40677
[92]	train-mlogloss:0.44139	eval-mlogloss:0.40284
[93]	train-mlogloss:0.43763	eval-mlogloss:0.39881
[94]	train-mlogloss:0.43399	eval-mlogloss:0.39500
[95]	train-mlogloss:0.43043	eval-mlogloss:0.39111
[96]	train-mlogloss:0.42690	eval-mlogloss:0.38723
[97]	train-mlogloss:0.42377	eval-mlogloss:0.38362
[98]	train-mlogloss:0.42034	eval-mlogloss:0.37989
[99]	train-mlogloss:0.41730	eval-mlogloss:0.37651
[100]	train-mlogloss:0.41403	eval-mlogloss:0.37292
[101]	train-mlogloss:0.41092	eval-mlogloss:0.36980
[102]	train-mlogloss:0.40751	eval-mlogloss:0.36620
[103]	train-mlogloss:0.40435	eval-mlogloss:0.36270
[104]	train-mlogloss:0.40096	eval-mlogloss:0.35901
[105]	train-mlogloss:0.39820	eval-mlogloss:0.35588
[106]	train-mlogloss:0.39518	eval-mlogloss:0.35277
[107]	train-mlogloss:0.39266	eval-mlogloss:0.35012
[108]	train-mlogloss:0.38956	eval-mlogloss:0.34683
[109]	train-mlogloss:0.38656	eval-mlogloss:0.34343
[110]	train-mlogloss:0.38366	eval-mlogloss:0.34025
[111]	train-mlogloss:0.38075	eval-mlogloss:0.33708
[112]	train-mlogloss:0.37777	eval-mlogloss:0.33397
[113]	train-mlogloss:0.37552	eval-mlogloss:0.33158
[114]	train-mlogloss:0.37293	eval-mlogloss:0.32859
[115]	train-mlogloss:0.37030	eval-mlogloss:0.32554
[116]	train-mlogloss:0.36768	eval-mlogloss:0.32251
[117]	train-mlogloss:0.36477	eval-mlogloss:0.31932
[118]	train-mlogloss:0.36253	eval-mlogloss:0.31704
[119]	train-mlogloss:0.35993	eval-mlogloss:0.31419
[120]	train-mlogloss:0.35746	eval-mlogloss:0.31138
[121]	train-mlogloss:0.35464	eval-mlogloss:0.30831
[122]	train-mlogloss:0.35218	eval-mlogloss:0.30559
[123]	train-mlogloss:0.35018	eval-mlogloss:0.30337
[124]	train-mlogloss:0.34770	eval-mlogloss:0.30067
[125]	train-mlogloss:0.34536	eval-mlogloss:0.29796
[126]	train-mlogloss:0.34335	eval-mlogloss:0.29555
[127]	train-mlogloss:0.34102	eval-mlogloss:0.29302
[128]	train-mlogloss:0.33869	eval-mlogloss:0.29035
[129]	train-mlogloss:0.33671	eval-mlogloss:0.28804
[130]	train-mlogloss:0.33482	eval-mlogloss:0.28607
[131]	train-mlogloss:0.33300	eval-mlogloss:0.28391
[132]	train-mlogloss:0.33082	eval-mlogloss:0.28154
[133]	train-mlogloss:0.32907	eval-mlogloss:0.27955
[134]	train-mlogloss:0.32729	eval-mlogloss:0.27756
[135]	train-mlogloss:0.32534	eval-mlogloss:0.27540
[136]	train-mlogloss:0.32358	eval-mlogloss:0.27353
[137]	train-mlogloss:0.32145	eval-mlogloss:0.27126
[138]	train-mlogloss:0.31939	eval-mlogloss:0.26899
[139]	train-mlogloss:0.31725	eval-mlogloss:0.26672
[140]	train-mlogloss:0.31525	eval-mlogloss:0.26455
[141]	train-mlogloss:0.31367	eval-mlogloss:0.26278
[142]	train-mlogloss:0.31164	eval-mlogloss:0.26050
[143]	train-mlogloss:0.31002	eval-mlogloss:0.25880
[144]	train-mlogloss:0.30814	eval-mlogloss:0.25659
[145]	train-mlogloss:0.30635	eval-mlogloss:0.25481
[146]	train-mlogloss:0.30476	eval-mlogloss:0.25296
[147]	train-mlogloss:0.30275	eval-mlogloss:0.25063
[148]	train-mlogloss:0.30109	eval-mlogloss:0.24889
[149]	train-mlogloss:0.29963	eval-mlogloss:0.24721
[150]	train-mlogloss:0.29828	eval-mlogloss:0.24587
[151]	train-mlogloss:0.29690	eval-mlogloss:0.24450
[152]	train-mlogloss:0.29551	eval-mlogloss:0.24294
[153]	train-mlogloss:0.29365	eval-mlogloss:0.24090
[154]	train-mlogloss:0.29210	eval-mlogloss:0.23922
[155]	train-mlogloss:0.29042	eval-mlogloss:0.23742
[156]	train-mlogloss:0.28900	eval-mlogloss:0.23586
[157]	train-mlogloss:0.28764	eval-mlogloss:0.23446
[158]	train-mlogloss:0.28601	eval-mlogloss:0.23281
[159]	train-mlogloss:0.28459	eval-mlogloss:0.23122
[160]	train-mlogloss:0.28318	eval-mlogloss:0.22965
[161]	train-mlogloss:0.28151	eval-mlogloss:0.22798
[162]	train-mlogloss:0.28031	eval-mlogloss:0.22660
[163]	train-mlogloss:0.27918	eval-mlogloss:0.22534
[164]	train-mlogloss:0.27762	eval-mlogloss:0.22371
[165]	train-mlogloss:0.27630	eval-mlogloss:0.22234
[166]	train-mlogloss:0.27498	eval-mlogloss:0.22086
[167]	train-mlogloss:0.27358	eval-mlogloss:0.21928
[168]	train-mlogloss:0.27245	eval-mlogloss:0.21805
[169]	train-mlogloss:0.27116	eval-mlogloss:0.21659
[170]	train-mlogloss:0.26996	eval-mlogloss:0.21536
[171]	train-mlogloss:0.26853	eval-mlogloss:0.21368
[172]	train-mlogloss:0.26737	eval-mlogloss:0.21236
[173]	train-mlogloss:0.26621	eval-mlogloss:0.21105
[174]	train-mlogloss:0.26513	eval-mlogloss:0.20978
[175]	train-mlogloss:0.26389	eval-mlogloss:0.20846
[176]	train-mlogloss:0.26267	eval-mlogloss:0.20703
[177]	train-mlogloss:0.26151	eval-mlogloss:0.20577
[178]	train-mlogloss:0.26053	eval-mlogloss:0.20458
[179]	train-mlogloss:0.25947	eval-mlogloss:0.20349
[180]	train-mlogloss:0.25838	eval-mlogloss:0.20219
[181]	train-mlogloss:0.25779	eval-mlogloss:0.20145
[182]	train-mlogloss:0.25701	eval-mlogloss:0.20061
[183]	train-mlogloss:0.25581	eval-mlogloss:0.19935
[184]	train-mlogloss:0.25467	eval-mlogloss:0.19808
[185]	train-mlogloss:0.25346	eval-mlogloss:0.19667
[186]	train-mlogloss:0.25239	eval-mlogloss:0.19552
[187]	train-mlogloss:0.25131	eval-mlogloss:0.19425
[188]	train-mlogloss:0.25028	eval-mlogloss:0.19318
[189]	train-mlogloss:0.24977	eval-mlogloss:0.19255
[190]	train-mlogloss:0.24874	eval-mlogloss:0.19138
[191]	train-mlogloss:0.24826	eval-mlogloss:0.19074
[192]	train-mlogloss:0.24736	eval-mlogloss:0.18965
[193]	train-mlogloss:0.24632	eval-mlogloss:0.18858
[194]	train-mlogloss:0.24524	eval-mlogloss:0.18748
[195]	train-mlogloss:0.24422	eval-mlogloss:0.18645
[196]	train-mlogloss:0.24378	eval-mlogloss:0.18595
[197]	train-mlogloss:0.24272	eval-mlogloss:0.18473
[198]	train-mlogloss:0.24204	eval-mlogloss:0.18401
[199]	train-mlogloss:0.24162	eval-mlogloss:0.18357
[200]	train-mlogloss:0.24069	eval-mlogloss:0.18257
[201]	train-mlogloss:0.23964	eval-mlogloss:0.18123
[202]	train-mlogloss:0.23877	eval-mlogloss:0.18032
[203]	train-mlogloss:0.23801	eval-mlogloss:0.17939
[204]	train-mlogloss:0.23758	eval-mlogloss:0.17884
[205]	train-mlogloss:0.23742	eval-mlogloss:0.17852
[206]	train-mlogloss:0.23733	eval-mlogloss:0.17841
[207]	train-mlogloss:0.23682	eval-mlogloss:0.17782
[208]	train-mlogloss:0.23642	eval-mlogloss:0.17739
[209]	train-mlogloss:0.23547	eval-mlogloss:0.17633
[210]	train-mlogloss:0.23503	eval-mlogloss:0.17565
[211]	train-mlogloss:0.23465	eval-mlogloss:0.17520
[212]	train-mlogloss:0.23424	eval-mlogloss:0.17467
[213]	train-mlogloss:0.23414	eval-mlogloss:0.17461
[214]	train-mlogloss:0.23374	eval-mlogloss:0.17409
[215]	train-mlogloss:0.23297	eval-mlogloss:0.17327
[216]	train-mlogloss:0.23258	eval-mlogloss:0.17262
[217]	train-mlogloss:0.23217	eval-mlogloss:0.17206
[218]	train-mlogloss:0.23183	eval-mlogloss:0.17156
[219]	train-mlogloss:0.23129	eval-mlogloss:0.17108
[220]	train-mlogloss:0.23124	eval-mlogloss:0.17104
[221]	train-mlogloss:0.23091	eval-mlogloss:0.17065
[222]	train-mlogloss:0.23004	eval-mlogloss:0.16977
[223]	train-mlogloss:0.22967	eval-mlogloss:0.16941
[224]	train-mlogloss:0.22921	eval-mlogloss:0.16890
[225]	train-mlogloss:0.22882	eval-mlogloss:0.16841
[226]	train-mlogloss:0.22841	eval-mlogloss:0.16794
[227]	train-mlogloss:0.22802	eval-mlogloss:0.16737
[228]	train-mlogloss:0.22767	eval-mlogloss:0.16697
[229]	train-mlogloss:0.22695	eval-mlogloss:0.16626
[230]	train-mlogloss:0.22660	eval-mlogloss:0.16581
[231]	train-mlogloss:0.22632	eval-mlogloss:0.16547
[232]	train-mlogloss:0.22629	eval-mlogloss:0.16538
[233]	train-mlogloss:0.22593	eval-mlogloss:0.16497
[234]	train-mlogloss:0.22567	eval-mlogloss:0.16459
[235]	train-mlogloss:0.22494	eval-mlogloss:0.16380
[236]	train-mlogloss:0.22456	eval-mlogloss:0.16329
[237]	train-mlogloss:0.22456	eval-mlogloss:0.16330
[238]	train-mlogloss:0.22451	eval-mlogloss:0.16328
[239]	train-mlogloss:0.22395	eval-mlogloss:0.16270
[240]	train-mlogloss:0.22384	eval-mlogloss:0.16265
[241]	train-mlogloss:0.22353	eval-mlogloss:0.16229
[242]	train-mlogloss:0.22323	eval-mlogloss:0.16197
[243]	train-mlogloss:0.22310	eval-mlogloss:0.16180
[244]	train-mlogloss:0.22280	eval-mlogloss:0.16142
[245]	train-mlogloss:0.22278	eval-mlogloss:0.16144
[246]	train-mlogloss:0.22274	eval-mlogloss:0.16140
[247]	train-mlogloss:0.22250	eval-mlogloss:0.16109
[248]	train-mlogloss:0.22238	eval-mlogloss:0.16090
[249]	train-mlogloss:0.22204	eval-mlogloss:0.16044
[250]	train-mlogloss:0.22174	eval-mlogloss:0.16004
[251]	train-mlogloss:0.22169	eval-mlogloss:0.15987
[252]	train-mlogloss:0.22113	eval-mlogloss:0.15928
[253]	train-mlogloss:0.22109	eval-mlogloss:0.15926
[254]	train-mlogloss:0.22085	eval-mlogloss:0.15896
[255]	train-mlogloss:0.22054	eval-mlogloss:0.15857
[256]	train-mlogloss:0.22021	eval-mlogloss:0.15817
[257]	train-mlogloss:0.21985	eval-mlogloss:0.15774
[258]	train-mlogloss:0.21952	eval-mlogloss:0.15722
[259]	train-mlogloss:0.21922	eval-mlogloss:0.15687
[260]	train-mlogloss:0.21917	eval-mlogloss:0.15681
[261]	train-mlogloss:0.21916	eval-mlogloss:0.15676
[262]	train-mlogloss:0.21884	eval-mlogloss:0.15626
[263]	train-mlogloss:0.21878	eval-mlogloss:0.15618
[264]	train-mlogloss:0.21848	eval-mlogloss:0.15578
[265]	train-mlogloss:0.21838	eval-mlogloss:0.15566
[266]	train-mlogloss:0.21800	eval-mlogloss:0.15504
[267]	train-mlogloss:0.21786	eval-mlogloss:0.15488
[268]	train-mlogloss:0.21777	eval-mlogloss:0.15474
[269]	train-mlogloss:0.21752	eval-mlogloss:0.15441
[270]	train-mlogloss:0.21724	eval-mlogloss:0.15404
[271]	train-mlogloss:0.21696	eval-mlogloss:0.15368
[272]	train-mlogloss:0.21694	eval-mlogloss:0.15368
[273]	train-mlogloss:0.21689	eval-mlogloss:0.15361
[274]	train-mlogloss:0.21685	eval-mlogloss:0.15352
[275]	train-mlogloss:0.21655	eval-mlogloss:0.15317
[276]	train-mlogloss:0.21654	eval-mlogloss:0.15312
[277]	train-mlogloss:0.21650	eval-mlogloss:0.15308
[278]	train-mlogloss:0.21614	eval-mlogloss:0.15267
[279]	train-mlogloss:0.21611	eval-mlogloss:0.15265
[280]	train-mlogloss:0.21581	eval-mlogloss:0.15228
[281]	train-mlogloss:0.21555	eval-mlogloss:0.15194
[282]	train-mlogloss:0.21551	eval-mlogloss:0.15191
[283]	train-mlogloss:0.21534	eval-mlogloss:0.15158
[284]	train-mlogloss:0.21534	eval-mlogloss:0.15158
[285]	train-mlogloss:0.21530	eval-mlogloss:0.15152
[286]	train-mlogloss:0.21507	eval-mlogloss:0.15121
[287]	train-mlogloss:0.21475	eval-mlogloss:0.15087
[288]	train-mlogloss:0.21470	eval-mlogloss:0.15085
[289]	train-mlogloss:0.21440	eval-mlogloss:0.15053
[290]	train-mlogloss:0.21408	eval-mlogloss:0.15010
[291]	train-mlogloss:0.21379	eval-mlogloss:0.14975
[292]	train-mlogloss:0.21377	eval-mlogloss:0.14973
[293]	train-mlogloss:0.21350	eval-mlogloss:0.14938
[294]	train-mlogloss:0.21341	eval-mlogloss:0.14929
[295]	train-mlogloss:0.21293	eval-mlogloss:0.14872
[296]	train-mlogloss:0.21267	eval-mlogloss:0.14840
[297]	train-mlogloss:0.21263	eval-mlogloss:0.14826
[298]	train-mlogloss:0.21259	eval-mlogloss:0.14821
[299]	train-mlogloss:0.21257	eval-mlogloss:0.14823

[I 2026-03-02 05:11:26,617] Trial 21 finished with value: 1.0 and parameters: {'lambda': 2.8427282287119184e-05, 'alpha': 0.012227456180268699, 'eta': 0.01001477131675934, 'gamma': 0.0023386972147137995, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.6684698441697745, 'colsample_bytree': 0.8304096994375526}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.03438	eval-mlogloss:1.03213
[1]	train-mlogloss:0.98710	eval-mlogloss:0.97913
[2]	train-mlogloss:0.93183	eval-mlogloss:0.91990
[3]	train-mlogloss:0.87704	eval-mlogloss:0.86268

[I 2026-03-02 05:11:26,857] Trial 22 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.05194	eval-mlogloss:1.05096
[1]	train-mlogloss:1.01673	eval-mlogloss:1.01300
[2]	train-mlogloss:0.97470	eval-mlogloss:0.96923
[3]	train-mlogloss:0.93407	eval-mlogloss:0.92623

[I 2026-03-02 05:11:26,915] Trial 23 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.01334	eval-mlogloss:1.01415

[I 2026-03-02 05:11:26,959] Trial 24 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04847	eval-mlogloss:1.04620
[1]	train-mlogloss:1.00238	eval-mlogloss:0.99749
[2]	train-mlogloss:0.95864	eval-mlogloss:0.95196
[3]	train-mlogloss:0.91629	eval-mlogloss:0.90859

[I 2026-03-02 05:11:27,027] Trial 25 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02695	eval-mlogloss:1.02338

[I 2026-03-02 05:11:27,076] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.82049	eval-mlogloss:0.79550

[I 2026-03-02 05:11:27,115] Trial 27 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07207	eval-mlogloss:1.07266
[1]	train-mlogloss:1.04165	eval-mlogloss:1.03937
[2]	train-mlogloss:1.01134	eval-mlogloss:1.00924
[3]	train-mlogloss:0.98139	eval-mlogloss:0.97760

[I 2026-03-02 05:11:27,182] Trial 28 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.94969	eval-mlogloss:0.94150

[I 2026-03-02 05:11:27,224] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02576	eval-mlogloss:1.02832

[I 2026-03-02 05:11:27,267] Trial 30 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08320	eval-mlogloss:1.08397
[1]	train-mlogloss:1.06849	eval-mlogloss:1.06855
[2]	train-mlogloss:1.05386	eval-mlogloss:1.05329
[3]	train-mlogloss:1.03905	eval-mlogloss:1.03813
[4]	train-mlogloss:1.02510	eval-mlogloss:1.02366
[5]	train-mlogloss:1.01091	eval-mlogloss:1.00836
[6]	train-mlogloss:0.99743	eval-mlogloss:0.99411
[7]	train-mlogloss:0.98452	eval-mlogloss:0.98044
[8]	train-mlogloss:0.97170	eval-mlogloss:0.96688
[9]	train-mlogloss:0.95889	eval-mlogloss:0.95318
[10]	train-mlogloss:0.94634	eval-mlogloss:0.94027
[11]	train-mlogloss:0.93421	eval-mlogloss:0.92764
[12]	train-mlogloss:0.92246	eval-mlogloss:0.91554
[13]	train-mlogloss:0.91062	eval-mlogloss:0.90304
[14]	train-mlogloss:0.89904	eval-mlogloss:0.89091
[15]	train-mlogloss:0.88743	eval-mlogloss:0.87862

[I 2026-03-02 05:11:27,414] Trial 31 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.07891	eval-mlogloss:1.07964
[1]	train-mlogloss:1.04933	eval-mlogloss:1.04853
[2]	train-mlogloss:1.02081	eval-mlogloss:1.01873
[3]	train-mlogloss:0.99223	eval-mlogloss:0.98955

[I 2026-03-02 05:11:27,488] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02777	eval-mlogloss:1.02513

[I 2026-03-02 05:11:27,531] Trial 33 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08486	eval-mlogloss:1.08582
[1]	train-mlogloss:1.07165	eval-mlogloss:1.07215
[2]	train-mlogloss:1.05838	eval-mlogloss:1.05825
[3]	train-mlogloss:1.04493	eval-mlogloss:1.04447
[4]	train-mlogloss:1.03231	eval-mlogloss:1.03161
[5]	train-mlogloss:1.01946	eval-mlogloss:1.01792
[6]	train-mlogloss:1.00730	eval-mlogloss:1.00549
[7]	train-mlogloss:0.99567	eval-mlogloss:0.99317
[8]	train-mlogloss:0.98392	eval-mlogloss:0.98059
[9]	train-mlogloss:0.97233	eval-mlogloss:0.96831
[10]	train-mlogloss:0.96091	eval-mlogloss:0.95654
[11]	train-mlogloss:0.94975	eval-mlogloss:0.94491
[12]	train-mlogloss:0.93885	eval-mlogloss:0.93359
[13]	train-mlogloss:0.92802	eval-mlogloss:0.92214
[14]	train-mlogloss:0.91748	eval-mlogloss:0.91125
[15]	train-mlogloss:0.90686	eval-mlogloss:0.90019

[I 2026-03-02 05:11:27,664] Trial 34 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:0.91189	eval-mlogloss:0.89880

[I 2026-03-02 05:11:27,747] Trial 35 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04059	eval-mlogloss:1.03890

[I 2026-03-02 05:11:27,796] Trial 36 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.79316	eval-mlogloss:0.76619

[I 2026-03-02 05:11:27,845] Trial 37 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01512	eval-mlogloss:1.01484

[I 2026-03-02 05:11:27,893] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05945	eval-mlogloss:1.05874
[1]	train-mlogloss:1.02208	eval-mlogloss:1.02034
[2]	train-mlogloss:0.98658	eval-mlogloss:0.98415
[3]	train-mlogloss:0.95304	eval-mlogloss:0.94997

[I 2026-03-02 05:11:27,948] Trial 39 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.01487	eval-mlogloss:1.02761

[I 2026-03-02 05:11:27,992] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07253	eval-mlogloss:1.07258
[1]	train-mlogloss:1.04719	eval-mlogloss:1.04655
[2]	train-mlogloss:1.02248	eval-mlogloss:1.02074
[3]	train-mlogloss:0.99814	eval-mlogloss:0.99544

[I 2026-03-02 05:11:28,100] Trial 41 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02149	eval-mlogloss:1.01621

[I 2026-03-02 05:11:28,150] Trial 42 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04795	eval-mlogloss:1.04672

[I 2026-03-02 05:11:28,817] Trial 43 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06998	eval-mlogloss:1.07006
[1]	train-mlogloss:1.04251	eval-mlogloss:1.04204
[2]	train-mlogloss:1.01614	eval-mlogloss:1.01442
[3]	train-mlogloss:0.99001	eval-mlogloss:0.98764

[I 2026-03-02 05:11:29,282] Trial 44 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.05992	eval-mlogloss:1.06621

[I 2026-03-02 05:11:29,389] Trial 45 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88724	eval-mlogloss:0.87274

[I 2026-03-02 05:11:29,429] Trial 46 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.84937	eval-mlogloss:0.82743

[I 2026-03-02 05:11:29,476] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92955	eval-mlogloss:0.93978

[I 2026-03-02 05:11:29,537] Trial 48 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03056	eval-mlogloss:1.02750

[I 2026-03-02 05:11:29,568] Trial 49 pruned. Trial was pruned at iteration 1.

In [8]:

!pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.7.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.7.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.47)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.29.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)
Downloading optuna_integration-4.7.0-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 kB 1.2 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.7.0

In [12]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()